//www2.hu-berlin.de/vivaldi/index.php?id=mV001&lang=it
require(['tools/data/Clusterer', 'tools/data/StringDistance', 'tools/lang/phonology/Phone'], function(Clusterer, StringDistance, Phone){
	QUnit.module('Clusterer');

	QUnit.test('test', function(){
		//construct the data
		var variants = [
				'Rèba',        'Cortina',     'Padola',    'Costalta',  'Auronzo',   'Pozzale',   'Verona',     'Cencenighe', 'Casan',      'Tarzo',      'Belluno',    'San Stino',  'Venezia',    'Crespadoro', 'Albisano',   'Montebello', 'Teolo',      'Romano',     'Vas',        'Tonezza',    'Vicenza',     'Lovadina',   'Campo San Martino', 'Istrana',   'Raldon',     'Meolo',     'Cerea',      'Fratta Polesine', 'Villa Estense', 'Cavarzare', 'Treviso',    'Italia'],
			words = [
				['la'	,        'el',          'al',        'al',        'il',        'al',        'el',         'el',         'al',         'al',         'al',         'el',         'el',         'el',         'el',         'el',         'el',         'el',         'al',         'el',         'el',          'el',         'el',                'el',        'el',         'el',        'el',         'el',              'el',            'e',         'el',         'lui'],
				['la',         'ra',          'la',        'la',        'la',        'la',        'la',         'la',         'la',         'la',         'la',         'a',          'ea',         'la',         'la',         'la',         'ea',         'a',          'la',         'la',         'la',          'a',          'a',                 'a',         'a',          'a',         'la',         'la',              'la',            'ea',        'ƚa',         'la'],
//				['n',          'un',          'n',         'un',        'un',        'un',        'n',          'n',          'n',          'n',          'n',          'un',         'un',         'un',         'n',          'n',          'un',         'n',          'n',          'n',          'un',          'n',          'n',                 'n',         'n',          'n',         'n',          'un',              'n',             'n',         'n',          'un'],
				['n',          'un',          'n',         'un',        'un',        'an',        'un',         'en',         'an',         'un',         'an',         'un',         'un',         'un',         'en',         'on',         'un',         'on',         'an',         'un',         'on',          'un',         'un',                'un',        'un',         'un',        'un',         'un',              'on',            'un',        'un',         'un'],
				['jɛga',       'aga',         'aga',       'aga',       'aga',       'ɛga',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',        'akwa',       'akwa',              'akwa',      'akwa',       'akwa',      'akwa',       'akwa',            'akwa',          'akwa',      'akwa',       'akwa'],
				['e',          'e',           'ɛ',         'e',         'ɛ',         'e',         'e',          'e',          'e',          'e',          'e',          'e',          'ze',         'e',          'e',          'ze',         'ze',         'ze',         'e',          'ze',         'ze',          'e',          'ze',                'ze',        'e',          'ze',        'e',          'ze',              'ze',            'ze',        'ze',         'ɛ'],
				['t͡ʃauda',    't͡ʃɔuda',     't͡ʃauda',   't͡ʃauda',   't͡ʃauda',   't͡ʃauða',   'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',       'kalda',      'kalda',             'kalda',     'kalda',      'kalda',     'kalda',      'kalda',           'kalda',         'kalda',     'kalde',      'kalda'],
				['aɲel',       'aɲel',        'aɲel',      'aɲel',      'aɲɛl',      'ketin',     'aɲɛl',       'ɲɛl',        'ɲɛl',        'ɲɛl',        'ɲɛl',        'ɲɛl',        'aɲɛo',       'aɲɛlo',      'aɲɛl',       'aɲelo',      'aɲɛo',       'aɲɛo',       'aɲɛl',       'aɲɛlo',      'aɲelo',       'ɲɛl',        'aɲɛo',              'aɲɛo',      'aɲɛ',        'aɲɛo',      'aɲɛl',       'pjegorin',        'aɲɛlo',         'pegorin',   'aɲɛo',       'aɲɛllo'],
				['ai',         'ai',          'ai',        'ai',        'ai',        'ai',        'ajo',        'ai',         'ai',         'ajo',        'ai',         'ajo',        'ad͡ʒo',      'ajo',        'ai',         'ajo',        'ajo',        'ajo',        'ai',         'ajo',        'ajo',         'ajo',        'ajo',               'ajo',       'ajo',        'ajo',       'ajo',        'aju',             'ajo',           'ajo',       'ajo',        'aʎio'],
				['agoʃt',      'agoʃto',      'agostu',    'agosto',    'agosto',    'agosto',    'agosto',     'agost',      'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',      'gosto',      'agosto',            'agosto',    'agosto',     'agosto',    'agosto',     'agosto',          'agosto',        'agosto',    'agosto',     'agosto'],
				['ala',        'uʒɔra',       'alɛ',       'ala',       'ala',       'ala',       'ala',        'ala',        'ala',        'ala',        'ala',        'aƚa',        'aƚa',        'ala',        'ala',        'ala',        'ala',        'aƚa',        'ala',        'ala',        'ala',         'aƚa',        'aƚa',               'ala',       'ala',        'aƚa',       'ala',        'ala',             'ala',           'aƚa',       'aƚa',        'ala'],
				['aut',        'ɔuto',        'autu',      'auto',      'auto',      'auto',      'alto',       'aut',        'alt',        'alt',        'alt',        'alθ',        'alto',       'alto',       'alt',        'alto',       'alto',       'alto',       'alt',        'alto',       'alto',        'alt',        'alto',              'alto',      'alto',       'alto',      'alto',       'alt',             'alto',          'alto',      'alto',       'alto'],
				['auter',      'ɔutro',       'auter',     'autro',     'autro',     'autro',     'altro',      'altro',      'altro',      'altro',      'altro',      'altro',      'altro',      'altro',      'alter',      'altro',      'altro',      'altro',      'altro',      'altro',      'altro',       'altro',      'altro',             'altro',     'altro',      'altro',     'altro',      'altro',           'antro',         'antro',     'altro',      'altro'],
				['dame',       'dame',        'dam',       'dame',      'dame',      'damin',     'dame',       'dame',       'dame',       'dame',       'dame',       'dami',       'dame',       'dame',       'dame',       'dame',       'dam',        'dame',       'dame',       'damene',     'dame',        'dame',       'dame',              'dame',      'dame',       'dame',      'dame',       'damene',          'dame',          'dame',      'dame',       'dammi'],
				['tɔk',        'tɔko',        'bukon',     'bokon',     'tɔko',      'tɔko',      'tɔko',       'tɔkh',       'tɔkh',       'tɔk',        'tɔk',        'tɔk',        'tɔko',       'tɔko',       'tɔk',        'tɔko',       'tɔko',       'tɔko',       'tokh',       'tɔko',       'tɔko',        'tok',        'tɔko',              'tɔko',      'tɔko',       'tɔko',      'tɔko',       'tɔku',            'tɔko',          'tɔko',      'tɔko',       'pet͡st͡so'],
				['and͡ʒelo',   'anʒelu',      'angel',     'angul',     'and͡ʒel',   'andol',     'and͡ʒelo',   'and͡ʒelo',   'and͡ʒelo',   'and͡ʒelo',   'andol',      'and͡ʒeo',    'and͡ʒeo',    'and͡ʒelo',   'and͡ʒelo',   'and͡ʒelo',   'and͡ʒeo',    'and͡ʒeo',    'and͡ʒelo',   'and͡ʒelo',   'and͡ʒelo',    'and͡ʒeo',    'and͡ʒeo',           'and͡ʒeo',   'and͡ʒelo',   'and͡ʒeo',   'and͡ʒelo',   'anzeu',           'andolo',        'and͡ʒeu',   'anxeo',      'and͡ʒelo'],
				['an',         'an',          'an',        'an',        'an',        'an',        'ano',        'an',         'an',         'an',         'an',         'ano',        'ano',        'ano',        'an',         'ano',        'ano',        'ano',        'an',         'ano',        'ano',         'ano',        'ano',               'ano',       'ano',        'ano',       'ano',        'anu',             'ano',           'anu',       'an',         'anno'],
				['auril',      'aprile',      'aprili',    'aprile',    'avril',     'aprile',    'april',      'auril',      'aprile',     'aprile',     'avril',      'aprile',     'aprile',     'aprile',     'avril',      'aprile',     'apriƚe',     'aprie',      'april',      'aprile',     'aprile',      'aprie',      'aprie',             'aprie',     'april',      'aprile',    'april',      'april',           'aprile',        'aprie',     'aprie',      'aprile'],
				['arʒent',     'ard͡zento',   'arðento',   'ardentu',   'ardento',   'arðento',   'ard͡ʒento',  'ardent',     'ard͡ʒento',  'ard͡ʒento',  'ardento',    'ard͡ʒento',  'arzento',    'ard͡ʒento',  'ard͡zent',   'ard͡ʒento',  'ard͡ʒento',  'arjento',    'ard͡ʒento',  'ard͡zento',  'ard͡ʒento',   'ard͡ʒentio', 'ard͡ʒento',         'ard͡ʒento', 'ard͡ʒento',  'ard͡ʒento', 'ard͡ʒento',  'ard͡zento',       'ard͡ʒento',     'ard͡ʒento', 'arxento',    'ard͡ʒento'],
				['auton',      'outon',       'utɔnu',     'otuno',     'autono',    'auton',     'autuno',     'autun',      'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',      'autuno',     'autuno',            'autuno',    'autuno',     'autuno',    'autuno',     'autuno',          'autuno',        'autuno',    'autuno',     'autunno'],
				['bek',        'bɛko',        'beku',      'beko',      'bɛko',      'bɛko',      'beko',       'bɛkh',       'bɛkh',       'bɛk',        'bɛkh',       'bɛk',        'bɛko',       'bɛko',       'bɛkh',       'bɛko',       'bɛko',       'bɛko',       'bɛkh',       'bɛko',       'bɛko',        'bɛk',        'bɛko',              'bɛko',      'beko',       'bɛko',      'bɛko',       'bɛko',            'bɛko',          'bɛko',      'bɛko',       'bɛkko'],
				['bel',        'bɛl',         'bel',       'bel',       'bɛl',       'bɛl',       'bɛlo',       'bɛl',        'bɛl',        'bɛl',        'bɛl',        'bɛl',        'bɛo',        'bɛlo',       'bɛl',        'bɛlo',       'bɛo',        'bɛo',        'bɛl',        'bɛlo',       'bɛlo',        'bɛo',        'bɛo',               'bɛo',       'belo',       'bɛo',       'bɛlo',       'bɛo',             'bɛƚo',          'bɛo',       'bɛo',        'bɛllo'],
				['bela',       'bɛla',        'bela',      'bela',      'bɛla',      'bɛla',      'bɛla',       'bɛla',       'bɛla',       'bɛa',        'bɛla',       'bɛa',        'bɛa',        'bɛla',       'bɛla',       'bɛla',       'bɛa',        'bɛa',        'bɛla',       'bɛla',       'bɛla',        'bɛa',        'bɛa',               'bɛa',       'bela',       'bɛa',       'bɛla',       'bɛa',             'bɛƚa',          'bɛa',       'bɛa',        'bɛlla'],
				['bjei',       'bjei',        'bi',        'bøi',       'bjei',      'bjei',      'bɛi',        'bjei',       'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',         'bɛi',        'bɛi',               'bɛi',       'bɛi',        'bɛi',       'bɛi',        'bɛi',             'bɛi',           'bɛi',       'bɛi',        'bɛlli'],
				['bele',       'bɛlis',       'bele',      'bele',      'bɛle',      'bɛle',      'bɛle',       'bɛle',       'bɛle',       'bɛe',        'bɛle',       'bɛe',        'bɛe',        'bɛle',       'bɛle',       'bɛle',       'bɛe',        'bɛe',        'bɛle',       'bɛle',       'bɛle',        'bɛe',        'bɛe',               'bɛe',       'bele',       'bɛe',       'bɛle',       'bɛe',             'bɛe',           'bɛe',       'bɛe',        'bɛlle'],
				['t͡ʃan',      't͡ʃan',       't͡ʃan',     't͡ʃøn',     't͡ʃan',     't͡ʃan',     'kan',        'kan',        'kan',        'kan',        'kan',        'kan',        'kan',        'kan',        'kã',         'kan',        'kan',        'kan',        'kan',        'kan',        'kan',         'kan',        'kan',               'kan',       'kan',        'kan',       'kan',        'kan',             'kan',           'kan',       'kan',        'kane'],
				['t͡ʃɛza',     't͡ʃaza',      't͡ʃeza',    't͡ʃida',    't͡ʃaza',    't͡ʃaza',    'kaza',       'kaza',       'kaza',       'kaza',       'kaza',       'kaza',       'kaza',       'kaza',       'ka',         'kaza',       'kaza',       'kaza',       'kaza',       'kaza',       'kaza',        'kaza',       'kaza',              'kaza',      'kaza',       'kaza',      'kaza',       'kaza',            'kaza',          'kaza',      'kaza',       'kaza'],
				['blank',      'bjanko',      'bjanku',    'bjanko',    'bjanko',    'bjant͡ʃo',  'bjanko',     'bjank',      'bjankh',     'bjank',      'bjank',      'bjanko',     'bjanko',     'bjanko',     'bjankh',     'bjanko',     'bjanko',     'bjanko',     'bjankh',     'bjanko',     'bjanko',      'bjanko',     'bjanko',            'bjanko',    'bjanko',     'bjanko',    'bjanko',     'bjanko',          'bjanko',        'bjanko',    'bjanko',     'bjanko'],
				['brat͡ʃ',     'brat͡so',     'braθu',     'braθo',     'braθo',     'braθ',      'braso',      'braθ',       'braθ',       'brat͡s',     'braθ',       'bras',       'braso',      'braso',      'bras',       'braso',      'braso',      'braso',      'braθ',       'braso',      'braso',       'bras',       'braso',             'braso',     'braso',      'braso',     'braθo',      'braso',           'braso',         'braso',     'braso',      'brat͡ʃt͡ʃjo'],
				['bot͡ʃa',     'bot͡ʃa',      'bot͡ʃa',    'bot͡ʃa',    'bot͡ʃa',    'bot͡ʃa',    'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',        'boka',       'boka',              'boka',      'boka',       'boka',      'boka',       'boka',            'boka',          'boka',      'boka',       'bokka'],
				['bun',        'bon',         'bon',       'bon',       'bon',       'bon',       'bɔn',        'bon',        'bɔn',        'bɔn',        'bɔn',        'bon',        'bon',        'bon',        'boo',        'bɔn',        'bon',        'bon',        'bon',        'bɔn',        'bɔn',         'bon',        'bon',               'bon',       'bon',        'bon',       'bɔn',        'bon',             'bɔn',           'bɔn',       'bon',        'bwono'],
				['bona',       'bɔna',        'bona',      'bona',      'bɔna',      'bona',      'bɔna',       'bona',       'bɔna',       'bɔna',       'bɔna',       'bona',       'bona',       'bona',       'bona',       'bɔna',       'bɔna',       'buna',       'bona',       'bɔna',       'bɔna',        'bona',       'bona',              'bona',      'bona',       'bona',      'bona',       'bona',            'bɔna',          'bɔna',      'bona',       'bwona'],
				['boɲ',        'boi',         'boɲ',       'boɲ',       'buoi',      'boi',       'bɔni',       'boiɲ',       'bɔni',       'bɔni',       'bɔni',       'boni',       'boni',       'boni',       'boni',       'bɔni',       'bɔni',       'boni',       'boni',       'bɔni',       'bɔni',        'boni',       'boni',              'boni',      'boni',       'boni',      'boni',       'boni',            'bɔni',          'bɔni',      'boni',       'bwoni'],
				['t͡ʃaut',     't͡ʃoudo',     't͡ʃauðu',   't͡ʃaudo',   't͡ʃaudo',   't͡ʃauðo',   'kaldo',      'kaut',       'kalt',       'kalt',       'kalt',       'kaldo',      'kaldo',      'kaldo',      'kald',       'kaldo',      'kaldo',      'kaldo',      'kalt',       'kaldo',      'kaldo',       'kaldo',      'kaldo',             'kaldo',     'kaldo',      'kaldo',     'kaldo',      'kaldu',           'kaldo',         'kaldo',     'kaldo',      'kaldo'],
				['nte',        'int͡se',      'θ',         'θ',         'inθe',      'inte',      'ne',         'ente',       'te',         'su',         'te',         'inte',       'ne',         'inte',       'ne',         'inte',       'ne',         'inte',       'inte',       'ne',         'inte',        'inte',       'inte',              'ne',        'ne',         'inte',      'ne',         'inte',            'inte',          'su',        'ne',         'nel'],
				['t͡ʃamaza',   't͡ʃameza',    't͡ʃameza',  't͡ʃamøda',  't͡ʃameza',  't͡ʃamiza',  'kamid͡ʒa',   'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',     'kamiza',      'kamiza',     'kamiza',            'kamiza',    'kamiza',     'kamiza',    'kamiza',     'kamiza',          'kamiza',        'kamiza',    'kamiza',     'kamit͡ʃja'],
				['t͡ʃanp',     't͡ʃanpo',     't͡ʃanpu',   't͡ʃanpo',   't͡ʃanpo',   't͡ʃanpu',   'kanpo',      'kanph',      'kanph',      'kanp',       'kanp',       'kanp',       'kanpo',      'kanpo',      'kanp',       'kanpo',      'kanpo',      'kanpo',      'kanp',       'kanpo',      'kanpo',       'kanp',       'kanpo',             'kanpo',     'kanpo',      'kanpo',     'kanpo',      'kanpu',           'kanpo',         'kanpo',     'kanpo',      'kampo'],
				['t͡ʃandala',  't͡ʃandera',   'kandɛla',   'kandøla',   'kandela',   'mɔkul',     'mɔkolo',     'kandɛla',    'kandela',    'kandea',     'kandela',    'kandea',     'kandea',     'kandela',    'kandela',    'kandela',    'kandea',     'kandea',     'kandela',    'kandela',    'kandɛla',     'kandea',     'kandɛa',            'kandea',    'kandela',    'kandea',    'kandela',    'kandea',          'kandeƚa',       'kandea',    'kandea',     'kandela'],
				['t͡ʃaveil',   't͡ʃaji',      't͡ʃavɛl',   't͡ʃavel',   't͡ʃavel',   't͡ʃavel',   'kavel',      'kavel',      'kavɛl',      'kavɛl',      'kavel',      'kavel',      'kaveo',      'kavejo',     'kavɛl',      'kavejo',     'kavejo',     'kavejo',     'kavel',      'kavejo',     'kavejo',      'kavel',      'kavejo',            'kaveo',     'kaveo',      'kaveo',     'kavejo',     'kaveju',          'kavejo',        'kavejo',    'kaveo',      'kapello'],
				['t͡ʃapel',    't͡ʃapɛl',     't͡ʃapel',   't͡ʃapel',   't͡ʃapɛl',   't͡ʃapɛl',   'kapɛ',       'kapɛl',      'kapɛl',      'kapɛl',      'kapɛl',      'kapɛl',      'kapɛo',      'kapɛlo',     'kapɛl',      'kapɛlo',     'kapɛo',      'kapɛl',      'kapɛl',      'kapɛlo',     'kapɛlo',      'kapɛl',      'kapɛo',             'kapɛo',     'kapɛ',       'kapɛl',     'kapɛl',      'kapɛo',           'kapɛƚo',        'kapɛo',     'kapɛo',      'kappello'],
				['t͡ʃoura',    't͡ʃɔura',     't͡ʃaura',   't͡ʃaura',   't͡ʃaura',   't͡ʃaura',   'kavra',      'kaura',      'kaura',      'kavera',     'kaura',      'kavra',      'kavra',      'kavra',      'kavra',      'kavra',      'kavara',     'kavra',      'kaura',      'kavra',      'kavra',       'kavara',     'kavara',            'kavara',    'kavara',     'kavara',    'kavara',     'kavara',          'kavara',        'kavara',    'kavara',     'kapra'],
				['t͡ʃarbon',   'karbon',      't͡ʃarbon',  't͡ʃarbon',  't͡ʃarbon',  't͡ʃarbon',  'karbon',     'karbon',     'garbon',     'karbon',     'karbon',     'karbon',     'karbon',     'karbon',     'karbou',     'karbon',     'karbon',     'karbon',     'karbon',     'karbon',     'karbon',      'karbon',     'karbon',            'karbone',   'karbon',     'karbon',    'karbon',     'karbon',          'karbon',        'karbon',    'karbon',     'karbone'],
				['t͡ʃɛrn',     'karne',       'karni',     't͡ʃarne',   't͡ʃarne',   'karne',     'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',       'karne',      'karne',             'karne',     'karne',      'karne',     'karne',      'karne',           'karne',         'karne',     'karne',      'karne'],
				['t͡ʃɛr',      'karo',        'karu',      'karo',      'karo',      't͡ʃaru',    'karo',       'kar',        'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',        'karo',       'karo',              'karo',      'karo',       'karo',      'karo',       'karu',            'karo',          'karu',      'karo',       'karo'],
				['t͡ʃar',      't͡ʃar',       't͡ʃar',     't͡ʃɛr',     't͡ʃar',     't͡ʃar',     'karo',       'kar',        'kar',        'kar',        'kar',        'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'kar',        'karo',       'karo',        'karo',       'karo',              'karo',      'karo',       'karo',      'karo',       'karu',            'karo',          'karu',      'karo',       'karro'],
				['morona',     't͡ʃadena',    't͡ʃadena',  't͡ʃadøna',  't͡ʃadena',  't͡ʃaðena',  'kadena',     'kaðena',     'kaðena',     'kadena',     'kadena',     'kadena',     'kaena',      'kadena',     'kadena',     'kadena',     'kaena',      'kaɛna',      'kaðena',     'kaena',      'kaena',       'kadena',     'kaena',             'kaena',     'kadena',     'kadena',    'kadena',     'kadena',          'kaena',         'kaena',     'kaena',      'katena'],
				['t͡ʃaval',    'kaal',        't͡ʃaval',   't͡ʃaval',   't͡ʃaval',   't͡ʃaval',   'kaval',      'kaval',      'kaval',      'kaval',      'kaval',      'kaval',      'kavaƚo',     'kavalo',     'kaval',      'kavalo',     'kavaƚo',     'kaval',      'kaval',      'kavalo',     'kavalo',      'kaval',      'kavaƚo',            'kavaƚo',    'kaval',      'kaval',     'kaval',      'kavaƚo',          'kavaƚo',        'kavaƚo',    'kavaƚo',     'kavallo'],
				['t͡ʃender',   't͡sendre',    'θender',    'θønder',    'θendre',    'θendre',    'senar',      'θender',     'θendro',     'sendre',     'θendro',     'sɛnere',     'sɛnere',     'senare',     'sendre',     'senare',     'senare',     'sendre',     'θendre',     'senare',     'senare',      'senere',     'senare',            'senere',    'sendre',     'senere',    'senda',      'senare',          'senare',        'senare',    'senere',     't͡ʃenere'],
				['t͡ʃant',     't͡sento',     'θentu',     'θentu',     'θento',     'θentu',     'sento',      'θento',      'θento',      'sento',      'θento',      'sento',      'sento',      'sento',      'sɛnto',      'sento',      'sento',      'sento',      'θento',      'sento',      'sento',       'sento',      'sento',             'sento',     'sɛnto',      'sento',     'θento',      'θento',           'θento',         'θento',     'sento',      't͡ʃento'],

				['t͡ʃara',     't͡sera',      'θɛra',      'θøra',      'θera',      'θera',      't͡ʃera',     'θera',       'θera',       'sera',       'θera',       't͡ʃera',     'sera',       'sera',       't͡ʃera',     't͡ʃɛra',     't͡ʃɛra',     'sera',       'θera',       't͡ʃɛra',     't͡ʃɛra',      'sera',       'sɛra',              'sera',      'sera',       't͡ʃera',    't͡ʃera',     'sera',            'sera',          't͡ʃera',    'sera',       't͡ʃera'],
				['t͡ʃarkle',   't͡ʃert͡ʃo',   'θert͡ʃu',   'θert͡ʃo',   'θert͡ʃo',   'θert͡ʃu',   'serkolo',    'θerkol',     'θert͡ʃo',    'serkol',     'θert͡ʃo',    'sert͡ʃo',    'sert͡ʃo',    'sert͡ʃo',    'serkol',     'sert͡ʃo',    't͡ʃert͡ʃo',  'sɛrt͡ʃo',    'θert͡ʃo',    'sɛrt͡ʃo',    'sɛrt͡ʃo',     'sert͡ʃol',   'sɛrt͡ʃo',           'sert͡ʃo',   'serkolo',    'sɛrt͡ʃo',   't͡ʃert͡ʃo',  'sert͡ʃu',         'sert͡ʃo',       'sert͡ʃo',   'sert͡ʃo',    't͡ʃerkjo'],
				['no',         'no',          'un',        'n',         'no',        'no',        'nɔ',         'nɔ',         'nɔ',         'no',         'nɔ',         'nɔ',         'nɔ',         'no',         'no',         'nɔ',         'no',         'no',         'nɔ',         'no',         'nɔ',          'no',         'nu',                'no',        'no',         'no',        'no',         'nɔ',              'no',            'nɔ',        'no',         'non'],
				['savɔve',     'sae',         'savau',     'savau',     'savɛo',     'savɛo',     'savevo',     'savɛi',      'savea',      'save',       'savɛe',      'savee',      'savevo',     'savɛo',      'savevo',     'saevo',      'saeo',       'saɛvo',      'save',       'savevo',     'savevo',      'savɛe',      'savevo',            'savevo',    'saea',       'saveo',     'savea',      'savɛvo',          'savea',         'saveo',     'savea',      'sapevo'],
				['ke',         'ke',          'k',         'k',         'ke',        'ke',        'kɛ',         'ke',         'ke',         'ke',         'ke',         'ke',         'kɛ',         'ke',         'ke',         'kɛ',         'k',          'ke',         'ke',         'k',          'ke',          'ga',         'ke',                'ke',        'ke',         'ke',        'kɛ',         'kɛ',              'k',             'gɛ',        'ke',         'ke'],
				['mɔrt',       'mɔrto',       'mɔrto',     'mɔrto',     'mɔrto',     'mɔrtu',     'mɔrto',      'mɔrt',       'mɔrth',      'mɔrt',       'mɔrt',       'mɔrt',       'mɔrto',      'mɔrto',      'mɔrto',      'mɔrto',      'mɔrt',       'mɔrto',      'mɔrt',       'mɔrto',      'mɔrto',       'mɔrt',       'mɔrto',             'mɔrto',     'mɔrto',      'mɔrto',     'mɔrto',      'mɔrto',           'mɔrto',         'mɔrto',     'mɔrto',      'morto'],
				['kle',        't͡ʃae',       't͡ʃai',     't͡ʃai',     't͡ʃave',    't͡ʃave',    't͡ʃave',     't͡ʃaf',      't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',      't͡ʃave',     't͡ʃave',            't͡ʃave',    't͡ʃave',     't͡ʃave',    't͡ʃave',     't͡ʃave',          't͡ʃave',        't͡ʃave',    't͡ʃave',     'kjave'],
				['t͡ʃel',      't͡ʃjel',      'θjel',      'θjel',      'θjelo',     'θjel',      't͡ʃel',      'θiɛl',       't͡ʃelo',     't͡ʃelo',     'θjɛl',       't͡ʃɛl',      'sjɛo',       't͡ʃelo',     't͡ʃɛl',      't͡ʃɛlo',     't͡ʃɛo',      't͡ʃɛl',      't͡ʃelo',     'sjelo',      't͡ʃɛlo',      't͡ʃɛl',      't͡ʃɛo',             't͡ʃelo',    't͡ʃel',      't͡ʃɛl',     't͡ʃel',      'siɛlo',           'sjeƚo',         't͡ʃɛo',     'sjel',       't͡ʃjelo'],
				['t͡ʃarjezja', 't͡ʃarjeza',   'θarjeza',   'θareda',    'θarjeza',   'θarjeza',   'sireza',     'θarjɛza',    'θareza',     'sareza',     'θareza',     'sarɛza',     'sarjeza',    'sareza',     'sireza',     'sarɛza',     'sarɛza',     'sjarɛza',    'θarjeza',    'sjarɛza',    'sareza',      'sarɛza',     'sarɛza',            'sarjɛza',   'sireza',     'sarɛza',    'sireza',     'sarɛza',          'sarɛza',        'sarɛza',    'sarɛza',     't͡ʃiljed͡ʒja'],
				['t͡ʃinkanta', 't͡sinkwanta', 'θinkwanta', 'θinkwanta', 'θinkwanta', 'θinkwanta', 'sinkwanta',  'θinkwanta',  'θinkwanta',  'sinkwanta',  'θinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'θinkwanta',  'sinkwanta',  'sinkwanta',   'sinkwanta',  'sinkwanta',         'sinkwanta', 'sinkwanta',  'sinkwanta', 'sinkwanta',  'sinkwanta',       'sinkwanta',     'sinkwanta', 'sinkwanta',  't͡ʃinkwanta'],
				['t͡ʃink',     't͡sinke',     'θinki',     'θinke',     'θinke',     'θinke',     'sinkwe',     'θink',       'θinkwe',     'sinkwe',     'θinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'θinkwe',     'sinkwe',     'sinkwe',      'sinkwe',     'sinkwe',            'sinkwe',    'sinkwe',     'sinkwe',    'sinkwe',     'sinkwe',          'sinkwe',        'sinkwe',    'sinkwe',     't͡ʃinkwe'],
				['t͡ʃeola',    't͡seola',     'θeula',     'θødla',     'θɛula',     'θeola',     'seola',      'θeola',      'θeola',      'segola',     'θeola',      'segoƚa',     'segoƚa',     'sɛula',      'seola',      'seola',      'seoja',      'sagoja',     'θeola',      'seola',      'seola',       'seoƚa',      'seoƚa',             'seoƚa',     'seola',      'segoƚa',    'seola',      'segwe',           'seoƚa',         'segwea',    'segoƚa',     't͡ʃipolla'],
				['kurtel',     'kortɛl',      'gurtel',    'kortel',    'kortɛl',    'gortɛl',    'kortɛl',     'kortɛl',     'kortɛl',     'kortɛl',     'kortɛl',     'kortɛl',     'kortɛo',     'kortɛlo',    'kortɛl',     'kortɛlo',    'kortɛo',     'kortɛl',     'kortɛl',     'kortɛlo',    'kortɛlo',     'kortɛl',     'kortɛo',            'kortɛo',    'kortɛl',     'kortɛl',    'kortɛl',     'kortɛo',          'kortɛo',        'kortɛo',    'kortɛl',     'koltello'],
				['ʃkomint͡ʃe', 'ʃkoment͡sa',  'skumanθa',  'skumiθje',  'skominθja', 'skomenθa',  'skominsjar', 'skomiθja',   'ʃkomiθjar',  'skominsjar', 'skominθjar', 'kominsjar',  'skominsjar', 'kumisjare',  'ʃkomisjar',  'ʃkumisjare', 'skumisjare', 'skuminsjar', 'ʃkumiθjar',  'skomisjare', 'skominsjare', 'skuminsjar', 'komisjare',         'kuminʃjar', 'skomisjar',  'komisjar',  'skomiʃjar',  'kuminsjar',       'skumiʃjar',     'komiʃjare', 'skominsjar', 'komint͡ʃjare'],
				['kontent',    'parswaso',    'kuntentu',  'kontento',  'kontɛnto',  'kuntɛnto',  'kontɛnto',   'kontent',    'kontent',    'kontɛnt',    'kontɛnt',    'kontento',   'kontento',   'kontento',   'kontɛnto',   'kontɛnto',   'kontento',   'kontento',   'kontent',    'kontɛnto',   'kontɛnto',    'kontɛnto',   'kontento',          'kontento',  'kontɛnto',   'kontɛnto',  'kontento',   'kontɛnto',        'kontɛnto',      'kontɛnto',  'kontento',   'kontento'],
				['kujɛrkle',   'kwɛrt͡ʃo',    'kwɛrt͡ʃu',  'kwɛrt͡ʃo',  'kwɛrt͡ʃo',  'kwɛrt͡ʃu',  'koɛrt͡ʃolu', 'kwɛrkol',    'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kovɛrt͡ʃo',  'kovɛrt͡ʃo',  'kwɛrt͡ʃo',   'kwɛrt͡ʃol',  'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kovɛrt͡ʃo',  'kwɛrt͡ʃo',    'kwɛrt͡ʃo',   'kovɛrt͡ʃo',         'kovɛrt͡ʃo', 'kwɛrt͡ʃolo', 'kovɛrt͡ʃo', 'kwɛrt͡ʃolo', 'kwɛrt͡ʃu',        'kwɛrt͡ʃo',      'kwɛrt͡ʃo',  'kwɛrt͡ʃo',   'kopɛrkjo'],
				['kɔrn',       'kɔrno',       'kɔrnu',     'kɔrno',     'kɔrno',     'kɔrno',     'kɔrno',      'kɔrn',       'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrn',       'kɔrno',      'kɔrno',       'kɔrno',      'kɔrno',             'kɔrno',     'kɔrno',      'kɔrno',     'kɔrno',      'kɔrnu',           'kɔrno',         'kɔrno',     'kɔrno',      'kɔrno'],
				['vat͡ʃa',     'armenta',     'vat͡ʃa',    'vat͡ʃa',    'vat͡ʃa',    'vat͡ʃa',    'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',        'vaka',       'vaka',              'vaka',      'vaka',       'vaka',      'vaka',       'vaka',            'vaka',          'vaka',      'vaka',       'mukka'],
				['doi',        'doi',         'ðɔi',       'dɔi',       'doi',       'ðoi',       'du',         'dɔi',        'doi',        'do',         'doi',        'du',         'dɔ',         'du',         'du',         'du',         'dɔ',         'dɔ',         'ðɔ',         'du',         'du',          'dɔ',         'do',                'do',        'du',         'du',        'du',         'du',              'du',            'du',        'do',         'due'],
				['kwosa',      'kɔʃa',        'kwisa',     'køisa',     'gangul',    'galɔn',     'galɔn',      'galɔn',      'galɔn',      'kulata',     'kɔsa',       'kwart',      'kosata',     'galɔn',      'galɔn',      'galɔn',      'kɔsja',      'kujata',     'slaka',      'galon',      'galon',       'kuƚata',     'kuƚata',            'kuƚata',    'galon',      'kɔsja',     'kosjata',    'kɔsja',           'ganba',         'kɔsja',     'kuƚata',     'koʃa'],
				['kot',        'koto',        'kwetu',     'køtu',      'kwɔto',     'kwɔto',     'kɔto',       'kɔt',        'kɔt',        'kɔt',        'kɔt',        'kɔt',        'kɔto',       'kɔto',       'kɔt',        'kɔto',       'kɔto',       'kuzina',     'kɔt',        'kɔto',       'kɔto',        'kɔt',        'kɔto',              'kɔto',      'kɔto',       'kuzina',    'kɔto',       'kɔto',            'kɔto',          'kɔto',      'kɔto',       'kɔtto'],
				['krouʃ',      'kroʃ',        'krozi',     'kros',      'kros',      'kros',      'krɔze',      'kros',       'kroze',      'kroze',      'kros',       'kroze',      'kroze',      'kroze',      'kros',       'krot͡ʃe',    'kroze',      'kroze',      'kros',       'kroze',      'kroze',       'kroze',      'kroze',             'kroze',     'krot͡ʃe',    'kroze',     'krot͡ʃe',    'kroze',           'kroze',         'kroze',     'kroze',      'krot͡ʃe'],
				['kuna',       'kuna',        'kune',      'kuna',      'kuna',      'kuna',      'kuna',       'kuna',       'kuna',       'kuna',       'kuna',       'kuna',       'kuƚa',       'kuna',       'kuna',       'kuna',       'kua',        'kuna',       'kuna',       'kuna',       'kuna',        'kuna',       'kuna',              'kuna',      'kuna',       'kuna',      'kuna',       'kuna',            'kuna',          'kuna',      'kuna',       'kulla'],
				['kwɔze',      'koe',         'kui',       'køi',       'kuzina',    'kwɔze',     'kozar',      'koze',       'kuzinar',    'kuzinar',    'kuzinar',    'kuzinar',    'kuzinar',    'kuzinare',   'kozer',      'kuzinare',   'kuzinare',   'kuzinar',    'kuzinar',    'kuzinare',   'kuzinare',    'kuzinar',    'kuzinare',          'kuzinar',   'kozere',     'kuzinar',   'kozar',      'kuzinar',         'kuzinare',      'kuzinare',  'kuzinar',    'kut͡ʃinare'],
				['kwor',       'kwɔre',       'kweri',     'køre',      'kwor',      'kwɔr',      'kɔr',        'kɔr',        'kɔr',        'kɔr',        'kɔr',        'kwɔr',       'kwɔr',       'kɔre',       'kɔr',        'kɔre',       'kɔre',       'kɔr',        'kor',        'kɔre',       'kɔre',        'kor',        'kore',              'kwɔr',      'kor',        'kwɔr',      'kɔr',        'kɔr',             'kwɔre',         'kwɔre',     'kɔr',        'kuɔre'],
				['me',         'mɛ',          'me',        'mɛ',        'mɛ',        'me',        'me',         'me',         'me',         'me',         'me',         'me',         'mɛ',         'me',         'mɛ',         'mɛ',         'mɛ',         'me',         'me',         'me',         'me',          'me',         'me',                'me',        'mɛ',         'me',        'me',         'mɛ',              'me',            'mɛ',        'me',         'mi'],
				['fɛʃ',        'fɛʃ',         'fa',        'fa',        'fɛi',       'faz',       'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',          'fa',         'fa',                'fa',        'fa',         'fa',        'fa',         'fa',              'fa',            'fa',        'fa',         'fa'],
				['mɛl',        'mal',         'mal',       'mal',       'mal',       'mal',       'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'ma',         'mal',        'mal',        'male',       'mal',         'mal',        'ma',                'mal',       'mal',        'mal',       'mal',        'ma',              'mae',           'mae',       'mal',        'male'],
				['dent',       'dɛnte',       'dentu',     'dento',     'ðɛnte',     'dɛnti',     'dɛnte',      'dent',       'dent',       'dɛnt',       'dent',       'dente',      'dente',      'dente',      'dent',       'dɛnte',      'dente',      'dente',      'dent',       'dɛnte',      'dɛnte',       'dent',       'dɛnte',             'dente',     'dɛnte',      'dente',     'dente',      'dɛnte',           'dɛnte',         'dɛnte',     'dente',      'dente'],
				['al',         'ɔm',          'ɔn',        'ɔn',        'ɔn',        'ɔn',        'ɔmu',        'ɔm',         'ɔn',         'ɔn',         'ɔn',         'ɔn',         'ɔmo',        'ɔmo',        'ɔm',         'ɔmo',        'ɔmo',        'ɔmo',        'ɔm',         'ɔmo',        'ɔmo',         'ɔn',         'ɔmo',               'ɔmo',       'ɔmo',        'ɔmo',       'ɔmo',        'ɔmo',             'ɔmo',           'ɔmo',       'ɔmo',        'wɔmo'],
				['trantadoi',  'trɛntadoi',   'trɛntaðoi', 'trentadɔi', 'trentadoi', 'trɛntaðɔi', 'trentadu',   'trentadɔi',  'trentaðoi',  'trentadɔ',   'trentaðoi',  'trentado',   'trentado',   'trentadu',   'trentadu',   'trentadu',   'trentadɔ',   'trentado',   'trentaðɔ',   'trentadu',   'trentadu',    'trentadɔ',   'trentadɔ',          'trentado',  'trentadu',   'trentadɔ',  'trentadu',   'trentadu',        'trentado',      'trentaðɔ',  'trentado',   'trentadue'],
				['dents',      'dɛntes',      'ðenti',     'dente',     'dɛnte',     'ðenti',     'dɛnti',      'dɛnti',      'ðenth',      'dɛnt',       'dent',       'denti',      'denti',      'denti',      'denti',      'dɛnti',      'denti',      'denti',      'ðent',       'dɛnti',      'denti',       'dent',       'dɛnti',             'denti',     'dɛnti',      'denti',     'denti',      'dɛnti',           'dɛnti',         'dɛnti',     'denti',      'denti'],
				['darta',      'dreta',       'destre',    'destra',    'dɛstra',    'ðreta',     'drita',      'dɛstra',     'dɛstra',     'dɛstra',     'dreta',      'dɛstra',     'dɛstra',     'destra',     'drita',      'dɛstra',     'dɛstra',     'dɛstra',     'dɛstra',     'dɛstra',     'dɛstra',      'dɛstra',     'dɛstra',            'dɛstra',    'dɛstra',     'dɛstra',    'drita',      'drita',           'dɛstra',        'dɛstra',    'drita',      'dɛstra'],
				['ades',       'adɛs',        'aðes',      'ades',      'aðɛs',      'ades',      'adeso',      'aðɛs',       'aðɛs',       'adɛs',       'aðɛs',       'adɛs',       'dɛso',       'adeso',      'adɛs',       'dɛso',       'adɛso',      'dɛso',       'aðɛs',       'dɛso',       'dɛso',        'adɛs',       'dɛso',              'adɛs',      'adɛso',      'adɛso',     'adɛso',      'adɛso',           'dɛso',          'adɛso',     'dɛso',       'adɛsso'],
				['t',          't',           't',         'in',        'te',        't',         'tɛ',         't',          'te',         'tu',         'te',         'tɛ',         'ti',         'tɛ',         'tɛ',         'tɛ',         'tɛ',         'te',         'tu',         'te',         'tɛ',          'te',         'te',                'te',        'tɛ',         'te',        'te',         'te',              'tɛ',            'te',        'te',         'ti'],
				['mus',        'as',          'az',        'az',        'vas',       'az',        'gɛ',         'a',          'a',          'a',          'a',          'dɛve',       'ga',         'ge',         'ge',         'ga',         'gɛ',         'ge',         'a',          'gɛ',         'gɛ',          'devi',       'gɛ',                'ga',        'gɛ',         'ga',        'gɛ',         'gɛ',              'gɛ',            'gɛ',        'ga',         'ai'],
				['d͡zi',       'd͡zi',        'ði',        'di',        'ði',        'di',        'andar',      'andar',      'andar',      'andar',      'andar',      'andar',      'andar',      'anare',      'nar',        'nare',       'anare',      'andar',      'andar',      'nare',       'nar',         'ndar',       'andare',            'andar',     'nar',        'andar',     'andar',      'andar',           'nare',          'andar',     'ndar',       'andare'],
				['det͡senber', 'det͡sɛnbre',  'deθenbar',  'diθenbre',  'deθenbre',  'deθenbre',  'dit͡ʃɛnbre', 'dit͡ʃɛnbre', 'dit͡ʃenbre', 'dit͡ʃɛnbre', 'deθɛnbre',   'dit͡ʃenbre', 'dit͡ʃɛnbre', 'disenbre',   'dit͡ʃenbre', 'dit͡ʃɛnbre', 'disenbre',   'disenbre',   'dit͡ʃɛnbre', 'disɛnbre',   'disɛnbre',    'dit͡ʃɛnbre', 'disɛnbre',          'disenbre',  'dit͡ʃɛnbre', 'disenbre',  'dit͡ʃenbre', 'desɛnbre',        'desɛnbre',      'disɛnbre',  'desenbre',   'dit͡ʃembre'],
				['dezdɔt',     'dizdɔto',     'dizdɔtu',   'dizdɔto',   'dizdɔto',   'dizdɔto',   'dizdɔto',    'dizdɔt',     'dit͡ʃɔto',   'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',    'dizdɔto',     'dizdɔto',    'dizdɔto',           'dizdɔto',   'dizdɔto',    'dizdɔto',   'dizdɔto',    'dizdɔto',         'dizdɔto',       'dizdɔto',   'dizdɔto',    'dit͡ʃjɔtto'],
				['dieʃ',       'djeʃ',        'djɛs',      'djøs',      'djeze',     'djeze',     'djeze',      'djɛs',       'djɛze',      'djeze',      'djɛze',      'djɛze',      'djeze',      'djeze',      'djeze',      'djɛze',      'djɛze',      'djeze',      'djɛze',      'djeze',      'djɛze',       'djɛze',      'djɛze',             'djɛze',     'djeze',      'djɛze',     'djeze',      'djɛze',           'djɛze',         'djɛze',     'djɛze',      'diet͡ʃi'],
				['di',         'di',          'di',        'di',        'di',        'ði',        'dir',        'di',         'dir',        'dir',        'dir',        'dir',        'dir',        'dire',       'di',         'dire',       'dire',       'dir',        'dir',        'dire',       'dire',        'dir',        'dire',              'dir',       'dir',        'dir',       'dir',        'dir',             'dire',          'dire',      'dir',        'dire'],
				['mi',         'jo',          'jɔ',        'jø',        'jo',        'jɔ',        'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',          'mi',         'mi',                'mi',        'mi',         'mi',        'mi',         'mi',              'mi',            'mi',        'mi',         'me'],
				['al',         'el',          'li',        'li',        'lui',       'al',        'el',         'ɛl',         'l',          'l',          'l',          'ɛl',         'ɛl',         'el',         'ɛl',         'l',          'eo',         'lu',         'l',          'el',         'el',          'lu',         'lu',                'lu',        'l',          'lu',        'el',         'el',              'el',            'lu',        'el',         'lui'],
				['dige',       'digo',        'digi',      'digo',      'ðigo',      'ðio',       'digo',       'dige',       'dige',       'dize',       'dige',       'dize',       'digo',       'digo',       'digo',       'digo',       'digo',       'dizo',       'dige',       'digo',       'digo',        'dize',       'digo',              'digo',      'digo',       'digo',      'digo',       'digo',            'digu',          'digo',      'digo',       'diko'],
				['diʃ',        'diʃ',         'dis',       'dis',       'dis',       'dis',       'dize',       'dis',        'dis',        'dize',       'dis',        'dize',       'dize',       'dize',       'dis',        'dize',       'dize',       'dize',       'dis',        'dize',       'dize',        'dize',       'dize',              'dize',      'dize',       'dize',      'dize',       'dize',            'dize',          'dize',      'dize',       'dit͡ʃe'],
				['dit',        'dito',        'ðitu',      'dito',      'dito',      'ðito',      'dito',       'dit',        'dith',       'dita',       'dita',       'dit',        'dito',       'dito',       'dit',        'dito',       'ito',        'dito',       'ðit',        'dito',       'dito',        'dita',       'dito',              'dito',      'dito',       'dito',      'dito',       'dito',            'dito',          'dito',      'dito',       'detto'],
				['ledɛl',      'deda',        'ðedal',     'dedal',     'dedal',     'deðal',     'djal',       'dedal',      'diðjal',     'didjal',     'deðjal',     'didjal',     'dizjal',     'deale',      'djal',       'deale',      'dizjae',     'deal',       'diðjal',     'deale',      'deale',       'didjal',     'ditae',             'dizjae',    'djal',       'didjal',    'deal',       'deal',            'dizjae',        'dizjae',    'didjal',     'ditale'],
				['deit',       'djedo',       'dɛiðu',     'døido',     'deðo',      'diðo',      'deo',        'det',        'deth',       'det',        'det',        'deo',        'deo',        'deo',        'djɛl',       'deo',        'deo',        'dɛo',        'det',        'deo',        'deo',         'deo',        'dɛo',               'deo',       'djɛl',       'deo',       'deo',        'dɛo',             'deo',           'deo',       'deo',        'dito'],
				['deit͡ʃ',     'djede',       'ðɛidi',     'døide',     'deðe',      'djeðe',     'dei',        'det',        'ðeth',       'det',        'dɛt',        'dɛi',        'dei',        'dei',        'dijɛi',      'dei',        'de',         'dei',        'ðɛt',        'dei',        'dei',         'dei',        'dɛi',               'dɛe',       'djɛi',       'dei',       'dei',        'dɛi',             'dei',           'dii',       'dei',        'diti'],
				['t͡ʃink',     't͡sinke',     'θink',      'θink',      'θinke',     'θinke',     'sinkwe',     'θink',       'θinkwe',     'sinkwe',     'θinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     't͡sinkwe',   'θinkwe',     'sinkwe',     'sinkwe',      'singwe',     'sinkwe',            'sinkwe',    'sinkwe',     'sinkwe',    'sinkwe',     'sinkwe',          'sinkwe',        'sinkwe',    'sinkwe',     't͡ʃinkwe'],
				['dodeʃ',      'dɔdeʃ',       'dɔðes',     'dodes',     'dodeze',    'dɔðeze',    'dɔdeze',     'dɔdes',      'dɔðeze',     'dɔdeze',     'dɔdeze',     'dɔdeze',     'dɔdeze',     'dɔdeze',     'dodeze',     'dɔdeze',     'dodeze',     'dodaze',     'dɔðeze',     'dodeze',     'dodeze',      'dɔdeze',     'dodeze',            'dodeze',    'dodeze',     'dɔdeze',    'dodeze',     'dodeze',          'dodaze',        'dɔdeze',    'dodeze',     'dodit͡ʃi'],
				['dout͡ʃ',     'dɔlt͡se',     'dɔlθi',     'dolθe',     'dolθe',     'ðɔlθ',      'dɔlse',      'dɔθ',        'dɔlθ',       'dɔls',       'dɔlθ',       'dɔls',       'dɔlse',      'dolse',      'dolt͡s',     'dɔlse',      'dolse',      'dolt͡se',    'dɔlθ',       'dolse',      'dolse',       'dɔls',       'dolse',             'dolse',     'dolso',      'dolse',     'dolse',      'dɔse',            'dɔlse',         'dɔlse',     'dolse',      'dolt͡ʃe'],
				['doman',      'doman',       'duman',     'doman',     'doman',     'doman',     'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔma',       'dɔman',      'doman',      'dɔman',      'dɔman',      'dɔman',      'doman',       'dɔman',      'dɔman',             'doman',     'doman',      'doman',     'doman',      'dɔman',           'diman',         'dɔman',     'diman',      'domani'],
				['domanja',    'domeɲa',      'dumɛnja',   'dmøɲa',     'domeɲa',    'ðomeɲa',    'domɛnika',   'domɛnega',   'ðomenega',   'domenega',   'domenega',   'domenega',   'domenega',   'domenega',   'domenika',   'domenega',   'domenega',   'domenega',   'domenega',   'domenega',   'domenega',    'domɛnega',   'domenega',          'domenega',  'duminika',   'domenega',  'duminika',   'domɛnega',        'domɛnega',      'domɛnega',  'domenega',   'domenika'],
				['doi',        'doi',         'dɔi',       'dɔi',       'doi',       'doi',       'du',         'dɔi',        'doi',        'dɔ',         'dɔi',        'dɔ',         'dɔ',         'du',         'du',         'dɔ',         'dɔ',         'du',         'dɔ',         'dɔ',         'du',          'dɔ',         'dɔ',                'do',        'du',         'dɔ',        'du',         'do',              'do',            'dɔ',        'do',         'due'],
				['ɔi',         'ɔme',         'ɔmi',       'ɔmin',      'ɔmins',     'ɔme',       'ɔmini',      'ɔmin',       'ɔmi',        'ɔmini',      'ɔn',         'ɔmini',      'ɔmeni',      'ɔmeni',      'ɔmini',      'ɔmini',      'ɔmini',      'ɔmini',      'ɔmi',        'ɔmeni',      'ɔmini',       'ɔmeni',      'ɔmini',             'ɔmeni',     'omeni',      'ɔmeni',     'ɔmini',      'ɔmani',           'ɔmani',         'ɔmeni',     'ɔmi',        'wɔmini'],
				['fɔmena',     'femena',      'fɛmena',    'fømna',     'femena',    'femena',    'femena',     'fɛmena',     'femena',     'femena',     'femena',     'femena',     'femena',     'femena',     'femena',     'femena',     'fɛmena',     'femena',     'femena',     'femena',     'femena',      'fɛmena',     'fɛmena',            'femena',    'femena',     'femena',    'femena',     'fɛmena',          'femena',        'femena',    'femena',     'femmina'],
				['fɔmene',     'femenes',     'fɛmeni',    'fømne',     'femene',    'femene',    'femene',     'fɛmene',     'femene',     'femene',     'femene',     'femene',     'femene',     'femene',     'femene',     'femene',     'fɛmene',     'femene',     'femene',     'femene',     'femene',      'femene',     'fɛmene',            'femene',    'femene',     'fɛmene',    'femene',     'fɛmene',          'femene',        'femene',    'femene',     'femmine'],
				['dur',        'duro',        'duru',      'duro',      'ðuro',      'ðuru',      'duro',       'dur',        'dur',        'dur',        'dur',        'duro',       'duro',       'duro',       'dur',        'duro',       'duro',       'duro',       'dur',        'duro',       'duro',        'duro',       'duro',              'duro',      'duro',       'duro',      'duro',       'duro',            'duro',          'duru',      'duro',       'duro'],
				['strak',      'ʃtrako',      'straku',    'strako',    'strako',    'strako',    'strako',     'strak',      'strakh',     'strak',      'strak',      'strak',      'strako',     'jako',       'strak',      'jako',       'stufo',      'stanko',     'strakh',     'strako',     'jako',        'stuf',       'stufo',             'stufo',     'strako',     'stufo',     'strako',     'strako',          'strako',        'strako',    'strako',     'stanko'],
				['iʃte',       'iʃtade',      'istjaði',   'istede',    'istjade',   'istaðe',    'ista',       'ista',       'ista',       'ista',       'ista',       'ista',       'ista',       'esta',       'ista',       'ista',       'ista',       'ista',       'ista',       'ista',       'ista',        'ista',       'ista',              'ista',      'ista',       'ista',      'ista',       'ista',            'ista',          'ista',      'ista',       'estate'],
				['fɛver',      'fɔuro',       'fauru',     'fauro',     'fauro',     'fauro',     'fabro',      'faure',      'fabro',      'favero',     'faore',      'fabro',      'fabro',      'majaro',     'ferar',      'feraro',     'favaro',     'favro',      'fauro',      'favro',      'favaro',      'favaro',     'favero',            'favero',    'ferar',      'favero',    'feraro',     'favero',          'favaro',        'favaro',    'favaro',     'fabbro'],
				['faut͡ʃ',     'fɔut͡ʃe',     'fauθi',     'fauθe',     'fauθe',     'fauθ',      'fɛro',       'fauθ',       'falθ',       'faldin',     'falθ',       'sezue',      'falt͡ʃe',    'sezolɔto',   'fɛr',        'falt͡ʃeto',  'falsa',      'false',      'falθ',       'false',      'falsa',       'faldin',     'falsa',             'falsin',    'fɛro',       'falsin',    'falt͡ʃeto',  'segeto',          'mesora',        'fɛro',      'falsin',     'falt͡ʃetto'],
				['sjɛrf',      'adɔra',       'sɛrvi',     'sɛrve',     'sɛrve',     'sɛrve',     'okɔr',       'dɔra',       'ðɔpera',     'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',      'dɔpera',     'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',       'sɛrve',      'sɛrve',             'sɛrve',     'dɔpera',     'sɛrve',     'dɔpera',     'sɛrve',           'sɛrve',         'sɛrve',     'dɔpera',     'uzare'],
				['sije',       'taja',        'taje',      'taje',      'sea',       'sea',       'tajar',      'sjɛga',      'tajar',      'tajar',      'tajar',      'taja',       'tad͡ʒare',   'tajare',     'tajar',      'tajar',      'taja',       'taja',       'tajar',      'falsar',     'tajare',      'tajar',      'tajar',             'tajar',     'tajar',      'tajar',     'tajar',      'tajare',          'tajar',         'tajare',    'tajar',      'taʎjare'],
				['fam',        'fame',        'fami',      'fame',      'fame',      'fame',      'fame',       'fam',        'fan',        'fan',        'fan',        'fame',       'fame',       'fame',       'fam',        'fame',       'fame',       'fame',       'fam',        'fame',       'fame',        'fame',       'fame',              'fame',      'fame',       'fame',      'fame',       'fame',            'fame',          'fame',      'fame',       'fame'],
				['ɛ',          'ei',          'ai',        'ei',        'ɛi',        'ɛi',        'gɔ',         'ai',         'ɔ',          'ɔ',          'ɔ',          'ɔ',          'gɔ',         'gɔ',         'gɔ',         'gɔ',         'gɔ',         'gɔ',         'ɔ',          'gɔ',         'gɔ',          'ɔ',          'gɔ',                'gɔ',        'gɔ',         'gɔ',        'gɔ',         'gɔ',              'gɔ',            'gɔ',        'gɔ',         'ɔ'],
				['fɛ',         'fei',         'fɛi',       'foi',       'fɛi',       'fɛi',       'far',        'fa',         'far',        'far',        'far',        'far',        'far',        'fare',       'far',        'fare',       'fare',       'far',        'far',        'fare',       'fare',        'far',        'fare',              'far',       'far',        'far',       'far',        'far',             'fare',          'fare',      'far',        'fare'],
				['fɛt͡se',     'fɛt͡so',      'faθi',      'faθo',      'fɛt͡so',    'faθo',      'fɔ',         'faθe',       'fae',        'fae',        'fae',        'fae',        'faso',       'faso',       'faso',       'faso',       'faso',       'faso',       'fae',        'faso',       'faso',        'fae',        'faso',              'faso',      'fao',        'fae',       'fao',        'fao',             'faso',          'faso',      'faso',       'fat͡ʃt͡ʃjo'],
				['fɛs',        'fɛʃ',         'fa',        'fa',        'fɛs',       'fas',       'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',          'fa',         'fa',                'fa',        'fa',         'fa',        'fa',         'fa',              'fa',            'fa',        'fa',         'fa'],
				['fat',        'fato',        'fatu',      'fato',      'fato',      'fato',      'fato',       'fat',        'fat',        'fat',        'fat',        'fat',        'fato',       'fato',       'fat',        'fato',       'fato',       'fato',       'fat',        'fato',       'fato',        'fat',        'fato',              'fato',      'fato',       'fato',      'fato',       'fato',            'fato',          'fato',      'fato',       'fatto'],
				['faure',      'febraro',     'febraru',   'forøi',     'febraru',   'febraro',   'febrar',     'febrajo',    'febrajo',    'febrajo',    'fevrɛr',     'febrajo',    'febrajo',    'febraro',    'fevrar',     'febraro',    'febraro',    'fevraro',    'febrajo',    'febraro',    'febraro',     'febraro',    'febraro',           'febraro',   'febrar',     'febraro',   'febrar',     'febraru',         'fevraro',       'febraro',   'febraro',    'febbrajo'],
				['fjɛrn',      'fɛr',         'fɛru',      'fɛro',      'fɛr',       'fɛr',       'fɛro',       'fɛr',        'fɛr',        'fɛr',        'fɛr',        'fɛro',       'fɛro',       'fɛro',       'fɛr',        'fɛro',       'fɛro',       'fɛr',        'fɛr',        'fɛro',       'fɛro',        'fɛro',       'fɛro',              'fɛro',      'fɛro',       'fɛro',      'fɛro',       'fɛru',            'fɛro',          'fɛro',      'fɛro',       'fɛrro'],
				['deʃtude',    'ʃtudar',      'destuze',   'estude',    'despea',    'ðestuda',   'zmorsar',    'destuza',    'stuzar',     'stuzar',     'stuzar',     'stuar',      'stuar',      'zmorsar',    'zmorsar',    'zmorsare',   'zmorsare',   'zmorsar',    'stuzar',     'smorsare',   'zmorsare',    'stuzar',     'stuar',             'stuar',     'zmorsar',    'stua',      'zmort͡sar',  'dezmorsar',       'zmorsare',      'stuar',     'stuar',      'speɲere'],
				['fen',        'fen',         'fjen',      'føɲ',       'fjɛn',      'fen',       'fjɛn',       'fɛn',        'fjɛn',       'fjɛn',       'fen',        'fjɛn',       'fjen',       'fen',        'fe',         'fen',        'fen',        'fen',        'fɛn',        'fjɛn',       'fen',         'fen',        'fɛn',               'fen',       'fɛn',        'fen',       'fjen',       'fen',             'fen',           'fen',       'fen',        'fjeno'],
				['fjol',       'fjol',        'fi',        'fi',        'fjol',      'fjɔl',      'fjɔl',       'fjɔl',       'fjɔl',       'fjɔl',       'fjɔl',       'fjɔl',       'fio',        'fjɔlo',      'fjɔl',       'fjɔlo',      'fjɔjo',      'fjɔl',       'fjɔl',       'fjɔjo',      'fjɔlo',       'fjɔl',       'fjɔƚo',             'fjɔl',      'fjɔl',       'fjɔl',      'fjɔl',       'fjɔjo',           'fjɔƚo',         'fjɔjo',     'fjɔl',       'fiʎjo'],
				['fil',        'firo',        'filu',      'filo',      'filo',      'filo',      'fil',        'fil',        'fil',        'fil',        'fil',        'fil',        'fiƚo',       'filo',       'fil',        'filo',       'fiƚo',       'fil',        'fil',        'filo',       'filo',        'fil',        'fiƚo',              'fiƚo',      'fil',        'fiƚo',      'filo',       'fiƚu',            'filu',          'fijo',      'fil',        'filo'],
				['t͡ʃɔf',      'fjɔr',        'fjɔr',      'fjɔr',      'fjor',      'fjɔr',      'fjɔr',       'fjɔr',       'fjɔr',       'fjɔr',       'fjɔr',       'fjɔr',       'fjɔr',       'fjɔre',      'fjɔr',       'fjɔre',      'fjore',      'fjɔr',       'fjɔr',       'fjɔre',      'fjɔre',       'fjɔr',       'fjɔre',             'fjɔr',      'fjɔr',       'fjɔr',      'fjɔr',       'fjor',            'fjore',         'fjɔre',     'fjor',       'fjore'],
				['foja',       'foja',        'fɔja',      'fɔja',      'fɔja',      'fwoja',     'foja',       'foja',       'foja',       'foja',       'foja',       'fɔja',       'fɔd͡ʒa',     'fɔja',       'foja',       'fɔja',       'fɔja',       'foja',       'foja',       'fɔja',       'fɔja',        'fɔja',       'fɔja',              'fɔja',      'foja',       'fɔja',      'foja',       'fɔja',            'fɔja',          'fɔja',      'fɔja',       'fɔʎja'],
				['foje',       'fojes',       'fɔi',       'fɔi',       'fɔe',       'fwoje',     'foje',       'foje',       'foje',       'foje',       'foje',       'fɔje',       'fɔd͡ʒe',     'fɔje',       'foje',       'fɔje',       'fɔje',       'foje',       'foje',       'fɔje',       'fɔje',        'fɔje',       'fɔje',              'fɔje',      'foe',        'fɔje',      'foje',       'fɔje',            'fɔje',          'fɔje',      'fɔje',       'fɔʎje'],
				['pjɛrt',      'pɛrde',       'pɛrd',      'pɛrd',      'pɛrde',     'pɛrde',     'mɔla',       'pɛrθ',       'pɛrðe',      'pɛrθ',       'perθ',       'pɛrd',       'pɛrde',      'pɛrde',      'pɛrde',      'pɛrde',      'pɛrd',       'pɛrde',      'pɛrθ',       'pɛrde',      'pɛrde',       'pɛrde',      'pɛrde',             'pɛrde',     'pɛrde',      'pɛrde',     'pɛrde',      'pɛrde',           'pɛrde',         'pɛrde',     'pɛrde',      'pɛrde'],
				['fradel',     'fardɛl',      'fra',       'fra',       'fraðɛl',    'farðɛl',    'fradɛl',     'fraðɛl',     'fraðɛl',     'fradɛl',     'farðɛl',     'fradɛl',     'fradɛƚo',    'fradelo',    'fradɛl',     'fradelo',    'fradɛƚo',    'fradɛl',     'fraðɛl',     'fradɛjo',    'fradɛlo',     'fraðɛl',     'fradɛƚo',           'fradɛƚo',   'fradɛl',     'fradɛl',    'fradɛl',     'fraðɛƚo',         'fradɛƚo',       'fraðɛƚo',   'fradɛl',     'fratɛllo'],
				['fret',       'fjedo',       'frɛiðu',    'frøido',    'freðo',     'fjeðo',     'fredo',      'frɛt',       'fret',       'frɛt',       'frɛt',       'fredo',      'fredo',      'fredo',      'frɛ',        'fredo',      'fredo',      'fredo',      'fret',       'frɛdo',      'fredo',       'frɛðo',      'fredo',             'fredo',     'fredo',      'fredo',     'fredo',      'frɛðo',           'freðo',         'freðo',     'fredo',      'freddo'],
				['fum',        'fun',         'fumu',      'fumo',      'fumo',      'fun',       'fumo',       'fum',        'fun',        'fun',        'fun',        'fumo',       'fumo',       'fumo',       'fum',        'fumo',       'fumo',       'fumo',       'fum',        'fumo',       'fumo',        'fun',        'fumo',              'fumo',      'fumo',       'fumo',      'fumo',       'fumo',            'fumo',          'fumo',      'fumo',       'fumo'],
				['fonk',       'font͡sa',     'fɔngu',     'fongo',     'fɔngo',     'fongol',    'fɔngo',      'fɔnk',       'fongo',      'fɔnk',       'fonk',       'fungo',      'fungo',      'fungo',      'fɔng',       'fungo',      'bujo',       'fongo',      'fɔnk',       'fungo',      'fungo',       'fongo',      'fongo',             'fongo',     'fongo',      'fungo',     'fɔngo',      'fungo',           'fungo',         'fungo',     'fongo',      'fungo'],
				['fuɔk',       'fɔ',          'fwɛgu',     'føgo',      'fwɔgo',     'fwo',       'fogo',       'fɔk',        'fogo',       'fogo',       'fok',        'fɔgo',       'fogo',       'fogo',       'fɔgo',       'fɔgo',       'fɔgo',       'fogo',       'fogo',       'fɔgo',       'fɔgo',        'fɔgo',       'fɔgo',              'fɔgo',      'fɔgo',       'fɔgo',      'fogo',       'fɔgo',            'fɔgo',          'fɔgo',      'fɔgo',       'fwɔko'],
				['gal',        'zal',         'gɛl',       'd͡ʒel',     'd͡ʒal',     'gal',       'gal',        'gal',        'gal',        'gal',        'gal',        'gal',        'gaƚo',       'galo',       'gal',        'galo',       'gaƚo',       'gal',        'gal',        'galo',       'galo',        'gal',        'gaƚo',              'gaƚo',      'gal',        'gal',       'galo',       'gaƚo',            'gaƚo',          'gaƚo',      'gal',        'gallo'],
				['pita',       'pita',        'pite',      'pita',      'pita',      'pita',      'galina',     'pita',       'pita',       'pita',       'pita',       'gaina',      'gaina',      'galina',     'galina',     'galina',     'gaina',      'gaina',      'pita',       'galina',     'galina',      'gaina',      'gaina',             'gaina',     'galina',     'gaina',     'galina',     'gaina',           'galina',        'gaina',     'pita',       'gallina'],
				['d͡ʒama',     'zanba',       'd͡ʒanbɲ',   'd͡ʒanba',   'd͡ʒanba',   'ganba',     'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',       'ganba',      'ganba',             'ganba',     'ganba',      'ganba',     'ganba',      'ganba',           'ganba',         'ganba',     'ganba',      'gamba'],
				['rota',       'rota',        'rota',      'rota',      'rota',      'rota',      'rɔta',       'rota',       'rota',       'rota',       'rota',       'rota',       'rota',       'rota',       'rota',       'rɔta',       'rɔta',       'rota',       'rota',       'rota',       'rɔta',        'rota',       'rɔta',              'rota',      'rota',       'rota',      'rota',       'rota',            'rota',          'rota',      'rota',       'rwɔta'],
				['d͡ʒat',      'zato',        'd͡ʒetu',    'd͡ʒet',     'gato',      'gat',       'gato',       'gat',        'gat',        'gat',        'gat',        'gat',        'gato',       'gato',       'gat',        'gato',       'gato',       'gato',       'gat',        'gato',       'gato',        'gat',        'gato',              'gato',      'gato',       'gato',      'gato',       'gato',            'gato',          'gato',      'gato',       'gatto'],
				['zenɛ',       'zenaro',      'd͡ʒenaju',  'd͡ʒenaro',  'd͡ʒenaro',  'jenaro',    'zenar',      'd͡ʒenajo',   'd͡ʒenajo',   'd͡ʒenajo',   'ðenɛr',      'd͡ʒenaro',   'd͡ʒenajo',   'd͡ʒenaro',   'd͡ʒenar',    'd͡ʒenaro',   'zenajo',     'jenaro',     'd͡ʒenaro',   'zenaro',     'd͡ʒenaro',    'd͡zenaro',   'zenaro',            'zenaro',    'zenar',      'zenaro',    'd͡ʒenar',    'zenaro',          'zenaro',        'jenaro',    'zenaro',     'd͡ʒennajo'],
				['zenogle',    'zenɔjo',      'dunɔjo',    'donojo',    'denojo',    'ðenojo',    'zenɔt͡ʃo',   'danɔt͡ʃo',   'denɔt͡ʃo',   'zenɔt͡ʃo',   'denɔt͡ʃo',   'zenɔt͡ʃo',   'zenɔt͡ʃo',   'zenɔt͡ʃo',   'zenɔt͡ʃo',   'genɔt͡ʃ',    'zanɔt͡ʃo',   'zenɔt͡ʃo',   'denɔt͡ʃo',   'denɔt͡ʃo',   'zanɔt͡ʃo',    'zenɔt͡ʃo',   'zenɔt͡ʃo',          'zenɔt͡ʃo',  'zenɔt͡ʃo',   'zenɔt͡ʃo',  'zenɔt͡ʃo',   'zenɔt͡ʃo',        'denɔt͡ʃo',      'zenɔt͡ʃo',  'zenɔt͡ʃo',   'd͡ʒinɔkkjo'],
				['zwɔk',       'zɔgo',        'dwegu',     'døgo',      'dwogo',     'ðwogo',     'zugo',       'dugo',       'dogo',       'dɔgo',       'dugo',       'zɔgo',       'zɔgo',       'zugo',       'zugo',       'zugo',       'zugo',       'zugo',       'dugo',       'dugo',       'zugo',        'zɔgo',       'd͡ʒogo',            'djɔgo',     'zugo',       'zjɔgo',     'zugo',       'zɔgu',            'dwɔgo',         'zɔgu',      'zɔgo',       'd͡ʒjɔko'],
				['xuɲ',        'xuɲo',        'duɲ',       'duɲe',      'd͡ʒuɲo',    'ðuɲo',      'd͡ʒuɲo',     'duɲ',        'd͡ʒuɲo',     'd͡ʒuɲo',     'duɲe',       'd͡ʒuɲo',     'd͡ʒuɲo',     'd͡ʒuɲo',     'd͡ʒuɲo',     'd͡ʒuɲo',     'd͡ʒuɲo',     'juɲo',       'd͡ʒuɲo',     'd͡ʒuɲo',     'd͡ʒuɲo',      'd͡ʒuɲo',     'd͡ʒuɲo',            'd͡ʒuɲo',    'd͡ʒuɲo',     'd͡ʒuɲo',    'd͡ʒuɲo',     'xuɲu',            'd͡ʒuɲo',        'd͡ʒuɲo',    'xuɲo',       'd͡ʒjuɲo'],
				['gran',       'gran',        'gran',      'grøn',      'gran',      'gran',      'grande',     'grant',      'granth',     'grant',      'grant',      'grando',     'grando',     'grande',     'grande',     'grande',     'grande',     'grando',     'grant',      'grande',     'grando',      'grando',     'grando',            'grando',    'grando',     'grando',    'grande',     'grandu',          'grando',        'rande',     'grando',     'grande'],
				['grɔs',       'grɔs',        'grɔsu',     'grɔso',     'pèt͡so',    'grɔs',      'grɔso',      'grɔs',       'grɔs',       'grɔs',       'grɔs',       'grɔs',       'grɔso',      'grɔso',      'grɔs',       'grɔso',      'grɔso',      'grɔso',      'grɔs',       'grɔso',      'grɔso',       'grɔs',       'grɔso',             'grɔso',     'grɔso',      'grɔso',     'grɔso',      'grɔsu',           'grɔso',         'rɔsu',      'grɔso',      'grɔsso'],
				['njɛr',       'aɲere',       'ind͡ʒeri',  'iɲøre',     'ɲere',      'iɲere',     'jɛri',       'end͡zeri',   'jeri',       'jɛr',        'jeri',       'jɛri',       'd͡ʒɛri',     'jɛri',       'd͡ʒɛri',     'jɛri',       'jɛri',       'jeri',       'jeri',       'jere',       'jɛri',        'jɛri',       'jeri',              'jɛri',      'jeri',       'jɛri',      'jeri',       'd͡ʒɛri',          'jɛri',          'jɛri',      'jɛri',       'jɛri'],
//				['',     '',       '',      '',        '',       '',       '',      '',          '',     '',     '',       '',         '',      '',          '',        '',         '',    '',     '',     '',      '',      '',        '',                '',      '',      '',    '',     '',              '',            '',       ''],
//				['',     '',       '',      '',        '',       '',       '',      '',          '',     '',     '',       '',         '',      '',          '',        '',         '',    '',     '',     '',      '',      '',        '',                '',      '',      '',    '',     '',              '',            '',       ''],
//				['',     '',       '',      '',        '',       '',       '',      '',          '',     '',     '',       '',         '',      '',          '',        '',         '',    '',     '',     '',      '',      '',        '',                '',      '',      '',    '',     '',              '',            '',       ''],
//				'Rèba',        'Cortina',     'Padola',    'Costalta',  'Auronzo',   'Pozzale',   'Verona',     'Cencenighe', 'Casan',      'Tarzo',      'Belluno',    'San Stino',  'Venezia',    'Crespadoro', 'Albisano',   'Montebello', 'Teolo',      'Romano',     'Vas',        'Tonezza',    'Vicenza',     'Lovadina',   'Campo San Martino', 'Istrana',   'Raldon',     'Meolo',     'Cerea',      'Fratta Polesine', 'Villa Estense', 'Cavarzare', 'Treviso',    'Italia'],
			],
			size = variants.length,
			matrix = [],
			costs = {
				insertion: 1,
				deletion: 1,
				//exchange: 0.5,
				matchingFn: function(from, to){
					if(from == to)
						return 0;
					var fromFeatures = Phone.convertStringIntoFeatures(from),
						toFeatures = Phone.convertStringIntoFeatures(to);
					return 0.5 + Phone.similarity(fromFeatures[0], toFeatures[0]);
				}
			},
			//costs = {insertion: 1, deletion: 1, modification: 0.5},
			i, j;
		for(i = 0; i < size; i ++){
			matrix[i] = [];
			for(j = i; j < size; j ++)
				matrix[i][j] = 0;
		}

		//extract IPA characters
		words = words.map(function(word){
			return word.map(function(w){
				return w.match(StringDistance.REGEX_UNICODE_SPLITTER);
			});
		});

		//calculate average of distances
		words.forEach(function(word){
			for(i = 0; i < size; i ++)
				for(j = i + 1; j < size; j ++)
					matrix[i][j] += StringDistance.getStructuralDistance(word[i], word[j], costs);
		});
		for(i = 0; i < size; i ++)
			for(j = i + 1; j < size; j ++)
				matrix[i][j] /= words.length;

		//calculate total distance for each variant
		var average = [],
			sum;
		for(i = 0; i < size; i ++){
			sum = 0;
			for(j = 0; j < i; j ++)
				sum += matrix[j][i];
			for(j = i + 1; j < size; j ++)
				sum += matrix[i][j];
			average.push({variant: variants[i], distance: sum / size});
		}
		average.sort(function(a, b){ return a.distance - b.distance; });
		console.log(average);
		console.log('minimum distance variant is ' + average[0].variant + ' with ' + average[0].distance.toFixed(4) + ', next is ' + average[1].variant + ' with ' + average[1].distance.toFixed(4));
		console.log('maximum distance variant is ' + average[average.length - 1].variant + ' with ' + average[average.length - 1].distance.toFixed(4));

		//cluster variants
		var response = Clusterer.cluster(matrix, variants);

console.log(response);
		equal(response.printedTree, '(((((((((((((Montebello|Vicenza:0.0343)|Crespadoro:0.0504)|Tonezza:0.0668)|Villa Estense:0.0896)|Teolo:0.1072)|(Cavarzare|Fratta Polesine:0.1129):0.1242)|(((((Istrana|Meolo:0.0562)|Campo San Martino:0.0697)|Treviso:0.0933)|Venezia:0.0975)|Romano:0.1095):0.1308)|(((Cerea|Verona:0.0716)|Raldon:0.0819)|Albisano:0.1374):0.1821)|((((Casan|Vas:0.0759)|Belluno:0.0872)|Tarzo:0.1065)|(Lovadina|San Stino:0.0825):0.1453):0.1834)|Cencenighe:0.2261)|(((Auronzo|Pozzale:0.1610)|Cortina:0.2021)|(Costalta|Padola:0.1642):0.2513):0.2966)|Rèba:0.3156)|Italia:0.3997)');
	});
});
