//www2.hu-berlin.de/vivaldi/index.php?id=mV001&lang=it
require(['tools/data/Clusterer', 'tools/data/StringDistance', 'tools/lang/phonology/Phone'], function(Clusterer, StringDistance, Phone){
	QUnit.module('Clusterer');

	QUnit.test('test', function(){
		//construct the data
		var variants = [
				'Rèba',        'Cortina',   'Padola',    'Costalta',  'Auronzo',   'Pozzale',   'Verona',     'Cencenighe', 'Casan',      'Tarzo',      'Belluno',    'San Stino',  'Venezia',    'Crespadoro', 'Albisano',   'Montebello', 'Teolo',      'Romano',     'Vas',        'Tonezza',    'Vicenza',     'Lovadina',   'Campo San Martino', 'Istrana',   'Raldon',     'Meolo',     'Cerea',      'Fratta Polesine', 'Villa Estense', 'Cavarzare', 'Treviso'],
			words = [
				['l'	,        'el',        'al',        'al',        'il',        'al',        'el',         'el',         'al',         'al',         'al',         'el',         'el',         'el',         'el',         'el',         'el',         'el',         'al',         'el',         'el',          'el',         'el',                'el',        'el',         'el',        'el',         'el',              'el',            'e',         'el'],
				['la'	,        'r',         'l',         'l',         'l',         'al',        'l',          'l',          'l',          'l',          'l',          'l',          'l',          'l',          'l',          'l',          'ɛ',          'l',          'l',          'l',          'l',           'l',          'l',                 'l',         'l',          'l',         'l',          'l',               'l',             'ɛ',         'l'],
				['la',         'ra',        'la',        'la',        'la',        'la',        'la',         'la',         'la',         'la',         'la',         'a',          'ea',         'la',         'la',         'la',         'ea',         'a',          'la',         'la',         'la',          'a',          'a',                 'a',         'a',          'a',         'la',         'la',              'la',            'ea',        'ƚa'],
				['jɛga',       'aga',       'aga',       'aga',       'aga',       'ɛga',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',       'akwa',        'akwa',       'akwa',              'akwa',      'akwa',       'akwa',      'akwa',       'akwa',            'akwa',          'akwa',      'akwa'],
				['e',          'e',         'ɛ',         'e',         'ɛ',         'e',         'e',          'e',          'e',          'e',          'e',          'e',          'xe',         'e',          'e',          'xe',         'xe',         'xe',         'e',          'xe',         'xe',          'e',          'xe',                'xe',        'e',          'xe',        'e',          'xe',              'xe',            'xe',        'xe'],
				['t͡ʃauda',    't͡ʃɔuda',   't͡ʃauda',   't͡ʃauda',   't͡ʃauda',   't͡ʃauða',   'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',      'kalda',       'kalda',      'kalda',             'kalda',     'kalda',      'kalda',     'kalda',      'kalda',           'kalda',         'kalda',     'kalde'],
				['aɲel',       'aɲel',      'aɲel',      'aɲel',      'aɲɛl',      'ketin',     'aɲɛl',       'ɲɛl',        'ɲɛl',        'ɲɛl',        'ɲɛl',        'ɲɛl',        'aɲɛo',       'aɲɛlo',      'aɲɛl',       'aɲelo',      'aɲɛo',       'aɲɛo',       'aɲɛl',       'aɲɛlo',      'aɲelo',       'ɲɛl',        'aɲɛo',              'aɲɛo',      'aɲɛ',        'aɲɛo',      'aɲɛl',       'pjegorin',        'aɲɛlo',         'pegorin',   'aɲɛo'],
				['ai',         'ai',        'ai',        'ai',        'ai',        'ai',        'ajo',        'ai',         'ai',         'ajo',        'ai',         'ajo',        'ad͡ʒo',      'ajo',        'ai',         'ajo',        'ajo',        'ajo',        'ai',         'ajo',        'ajo',         'ajo',        'ajo',               'ajo',       'ajo',        'ajo',       'ajo',        'aju',             'ajo',           'ajo',       'ajo'],
				['agoʃt',      'agoʃto',    'agostu',    'agosto',    'agosto',    'agosto',    'agosto',     'agost',      'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',     'agosto',      'gosto',      'agosto',            'agosto',    'agosto',     'agosto',    'agosto',     'agosto',          'agosto',        'agosto',    'agosto'],
				['ala',        'uʒɔra',     'alɛ',       'ala',       'ala',       'ala',       'ala',        'ala',        'ala',        'ala',        'ala',        'aƚa',        'aƚa',        'ala',        'ala',        'ala',        'ala',        'aƚa',        'ala',        'ala',        'ala',         'aƚa',        'aƚa',               'ala',       'ala',        'aƚa',       'ala',        'ala',             'ala',           'aƚa',       'aƚa'],
				['àut',        'ɔuto',      'àutu',      'àuto',      'àuto',      'àuto',      'àlto',       'àut',        'àlt',        'àlt',        'àlt',        'àlθ',        'àlto',       'àlto',       'àlt',        'àlto',       'àlto',       'àlto',       'àlt',        'àlto',       'àlto',        'àlt',        'àlto',              'àlto',      'àlto',       'àlto',      'àlto',       'àlt',             'àlto',          'àlto',      'àlto'],
				['àuter',      'ɔutro',     'àuter',     'àutro',     'àutro',     'àutro',     'àltro',      'àltro',      'àltro',      'àltro',      'àltro',      'àltro',      'àltro',      'àltro',      'àlter',      'àltro',      'àltro',      'àltro',      'àltro',      'àltro',      'àltro',       'àltro',      'àltro',             'àltro',     'àltro',      'àltro',     'àltro',      'àltro',           'àntro',         'àntro',     'àltro'],
				['dame',       'dame',      'dam',       'dame',      'dame',      'damin',     'dame',       'dame',       'dame',       'dame',       'dame',       'dami',       'dame',       'dame',       'dame',       'dame',       'dam',        'dame',       'dame',       'damene',     'dame',        'dame',       'dame',              'dame',      'dame',       'dame',      'dame',       'damene',          'dame',          'dame',      'dame'],
				['n',          'un',        'n',         'un',        'un',        'un',        'n',          'n',          'n',          'n',          'n',          'un',         'un',         'un',         'n',          'n',          'un',         'n',          'n',          'n',          'un',          'n',          'n',                 'n',         'n',          'n',         'n',          'un',              'n',             'n',         'n'],
				['tɔk',        'tɔko',      'bukon',     'bokon',     'tɔko',      'tɔko',      'tɔko',       'tɔkh',       'tɔkh',        'tɔk',       'tɔk',        'tɔk',        'tɔko',       'tɔko',       'tɔk',        'tɔko',       'tɔko',       'tɔko',       'tokh',       'tɔko',       'tɔko',        'tok',        'tɔko',              'tɔko',      'tɔko',       'tɔko',      'tɔko',       'tɔku',            'tɔko',          'tɔko',      'tɔko'],
				['and͡ʒelo',   'anʒelu',    'angel',     'angul',     'and͡ʒel',   'andol',     'and͡ʒelo',   'and͡ʒelo',   'and͡ʒelo',   'and͡ʒelo',   'andol',      'and͡ʒeo',    'and͡ʒeo',    'and͡ʒelo',   'and͡ʒelo',   'and͡ʒelo',   'and͡ʒeo',    'and͡ʒeo',    'and͡ʒelo',   'and͡ʒelo',   'and͡ʒelo',    'and͡ʒeo',    'and͡ʒeo',           'and͡ʒeo',   'and͡ʒelo',   'and͡ʒeo',   'and͡ʒelo',   'anxeu',           'andolo',        'and͡ʒeu',   'and͡ʒeo'],
				['an',         'an',        'an',        'an',        'an',        'an',        'ano',        'an',         'an',         'an',         'an',         'ano',        'ano',        'ano',        'an',         'ano',        'ano',        'ano',        'an',         'ano',        'ano',         'ano',        'ano',               'ano',       'ano',        'ano',       'ano',        'anu',             'ano',           'anu',       'an'],
				['auril',      'aprile',    'aprili',    'aprile',    'avril',     'aprile',    'april',      'auril',      'aprile',     'aprile',     'avril',      'aprile',     'aprile',     'aprile',     'avril',      'aprile',     'apriƚe',     'aprie',      'april',      'aprile',     'aprile',      'aprie',      'aprie',             'aprie',     'april',      'aprile',    'april',      'april',           'aprile',        'aprie',     'aprie'],
				['arʒent',     'arzento',   'arðento',   'ardentu',   'ardento',   'arðento',   'ard͡ʒento',  'ardent',     'ard͡ʒento',  'ard͡ʒento',  'ardento',    'ard͡ʒento',  'arxento',    'ard͡ʒento',  'arzent',     'ard͡ʒento',  'ard͡ʒento',  'arjento',    'ard͡ʒento',  'arzento',    'ard͡ʒento',   'ard͡ʒentio', 'ard͡ʒento',         'ard͡ʒento', 'ard͡ʒento',  'ard͡ʒento', 'ard͡ʒento',  'arzento',         'ard͡ʒento',     'ard͡ʒento', 'ard͡ʒento'],
				['auton',      'outon',     'utɔnu',     'otuno',     'autono',    'auton',     'autuno',     'autun',      'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',     'autuno',      'autuno',     'autuno',            'autuno',    'autuno',     'autuno',    'autuno',     'autuno',          'autuno',        'autuno',    'autuno'],
				['bek',        'bɛko',      'beku',      'beko',      'bɛko',      'bɛko',      'beko',       'bɛkh',       'bɛkh',       'bɛk',        'bɛkh',       'bɛk',        'bɛko',       'bɛko',       'bɛkh',       'bɛko',       'bɛko',       'bɛko',       'bɛkh',       'bɛko',       'bɛko',        'bɛk',        'bɛko',              'bɛko',      'beko',       'bɛko',      'bɛko',       'bɛko',            'bɛko',          'bɛko',      'bɛko'],
				['bel',        'bɛl',       'bel',       'bel',       'bɛl',       'bɛl',       'bɛlo',       'bɛl',        'bɛl',        'bɛl',        'bɛl',        'bɛl',        'bɛo',        'bɛlo',       'bɛl',        'bɛlo',       'bɛo',        'bɛo',        'bɛl',        'bɛlo',       'bɛlo',        'bɛo',        'bɛo',               'bɛo',       'belo',       'bɛo',       'bɛlo',       'bɛo',             'bɛƚo',          'bɛo',       'bɛo'],
				['bela',       'bɛla',      'bela',      'bela',      'bɛla',      'bɛla',      'bɛla',       'bɛla',       'bɛla',       'bɛa',        'bɛla',       'bɛa',        'bɛa',        'bɛla',       'bɛla',       'bɛla',       'bɛa',        'bɛa',        'bɛla',       'bɛla',       'bɛla',        'bɛa',        'bɛa',               'bɛa',       'bela',       'bɛa',       'bɛla',       'bɛa',             'bɛƚa',          'bɛa',       'bɛa'],
				['bjei',       'bjei',      'bi',        'böi',       'bjei',      'bjei',      'bɛi',        'bjei',       'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',        'bɛi',         'bɛi',        'bɛi',               'bɛi',       'bɛi',        'bɛi',       'bɛi',        'bɛi',             'bɛi',           'bɛi',       'bɛi'],
				['bele',       'bɛlis',     'bele',      'bele',      'bɛle',      'bɛle',      'bɛle',       'bɛle',       'bɛle',       'bɛe',        'bɛle',       'bɛe',        'bɛe',        'bɛle',       'bɛle',       'bɛle',       'bɛe',        'bɛe',        'bɛle',       'bɛle',       'bɛle',        'bɛe',        'bɛe',               'bɛe',       'bele',       'bɛe',       'bɛle',       'bɛe',             'bɛe',           'bɛe',       'bɛe'],
				['t͡ʃan',      't͡ʃan',     't͡ʃan',     't͡ʃön',     't͡ʃan',     't͡ʃan',     'kan',        'kan',        'kan',        'kan',        'kan',        'kan',        'kan',        'kan',        'kã',         'kan',        'kan',        'kan',        'kan',        'kan',        'kan',         'kan',        'kan',               'kan',       'kan',        'kan',       'kan',        'kan',             'kan',           'kan',       'kan'],
				['n',          'un',        'n',         'un',        'n',         'an',        'un',         'en',         'an',         'un',         'an',         'un',         'un',         'un',         'en',         'on',         'un',         'on',         'an',         'un',         'on',          'un',         'un',                'un',        'un',         'un',        'un',         'un',              'on',            'un',        'un'],
				['t͡ʃɛxa',     't͡ʃaxa',    't͡ʃexa',    't͡ʃida',    't͡ʃaxa',    't͡ʃaxa',    'kaxa',       'kaxa',       'kaxa',       'kaxa',       'kaxa',       'kaxa',       'kaxa',       'kaxa',       'ka',         'kaxa',       'kaxa',       'kaxa',       'kaxa',       'kaxa',       'kaxa',        'kaxa',       'kaxa',              'kaxa',      'kaxa',       'kaxa',      'kaxa',       'kaxa',            'kaxa',          'kaxa',      'kaxa'],
				['blank',      'bjanko',    'bjanku',    'bjanko',    'bjanko',    'bjant͡ʃo',  'bjanko',     'bjank',      'bjankh',     'bjank',      'bjank',      'bjanko',     'bjanko',     'bjanko',     'bjankh',     'bjanko',     'bjanko',     'bjanko',     'bjankh',     'bjanko',     'bjanko',      'bjanko',     'bjanko',            'bjanko',    'bjanko',     'bjanko',    'bjanko',     'bjanko',          'bjanko',        'bjanko',    'bjanko'],
				['bot͡ʃa',     'bot͡ʃa',    'bot͡ʃa',    'bot͡ʃa',    'bot͡ʃa',    'bot͡ʃa',    'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',       'boka',        'boka',       'boka',              'boka',      'boka',       'boka',      'boka',       'boka',            'boka',          'boka',      'boka'],
				['brat͡ʃ',     'brazo',     'braθu',     'braθo',     'braθo',     'braθ',      'braso',      'braθ',       'braθ',       'braz',       'braθ',       'bras',       'braso',      'braso',      'bras',       'braso',      'braso',      'braso',      'braθ',       'braso',      'braso',       'bras',       'braso',             'braso',     'braso',      'braso',     'braθo',      'braso',           'braso',         'braso',     'braso'],
				['bun',        'bon',       'bon',       'bon',       'bon',       'bon',       'bɔn',        'bon',        'bɔn',        'bɔn',        'bɔn',        'bon',        'bon',        'bon',        'boo',        'bɔn',        'bon',        'bon',        'bon',        'bɔn',        'bɔn',         'bon',        'bon',               'bon',       'bon',        'bon',       'bɔn',        'bon',             'bɔn',           'bɔn',       'bon'],
				['bona',       'bɔna',      'bona',      'bona',      'bɔna',      'bona',      'bɔna',       'bona',       'bɔna',       'bɔna',       'bɔna',       'bona',       'bona',       'bona',       'bona',       'bɔna',       'bɔna',       'buna',       'bona',       'bɔna',       'bɔna',        'bona',       'bona',              'bona',      'bona',       'bona',      'bona',       'bona',            'bɔna',          'bɔna',      'bona'],
				['boɲ',        'boi',       'boɲ',       'boɲ',       'buoi',      'boi',       'bɔni',       'boiɲ',       'bɔni',       'bɔni',       'bɔni',       'boni',       'boni',       'boni',       'boni',       'bɔni',       'bɔni',       'boni',       'boni',       'bɔni',       'bɔni',        'boni',       'boni',              'boni',      'boni',       'boni',      'boni',       'boni',            'bɔni',          'bɔni',      'boni'],
				['t͡ʃaut',     't͡ʃoudo',   't͡ʃauðu',   't͡ʃaudo',   't͡ʃaudo',   't͡ʃauðo',   'kaldo',      'kaut',       'kalt',       'kalt',       'kalt',       'kaldo',      'kaldo',      'kaldo',      'kald',       'kaldo',      'kaldo',      'kaldo',      'kalt',       'kaldo',      'kaldo',       'kaldo',      'kaldo',             'kaldo',     'kaldo',      'kaldo',     'kaldo',      'kaldu',           'kaldo',         'kaldo',     'kaldo'],
				['nte',        'inze',      'θ',         'θ',         'inθe',      'inte',      'ne',         'ente',       'te',         'su',         'te',         'inte',       'ne',         'inte',       'ne',         'inte',       'ne',         'inte',       'inte',       'ne',         'inte',        'inte',       'inte',              'ne',        'ne',         'inte',      'ne',         'inte',            'inte',          'su',        'ne'],
				['t͡ʃamaxa',   't͡ʃamexa',  't͡ʃamexa',  't͡ʃamöda',  't͡ʃamexa',  't͡ʃamixa',  'kamid͡ʒa',   'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',     'kamixa',      'kamixa',     'kamixa',            'kamixa',    'kamixa',     'kamixa',    'kamixa',     'kamixa',          'kamixa',        'kamixa',    'kamixa'],
				['t͡ʃanp',     't͡ʃanpo',   't͡ʃanpu',   't͡ʃanpo',   't͡ʃanpo',   't͡ʃanpu',   'kanpo',      'kanph',      'kanph',      'kanp',       'kanp',       'kanp',       'kanpo',      'kanpo',      'kanp',       'kanpo',      'kanpo',      'kanpo',      'kanp',       'kanpo',      'kanpo',       'kanp',       'kanpo',             'kanpo',     'kanpo',      'kanpo',     'kanpo',      'kanpu',           'kanpo',         'kanpo',     'kanpo'],
				['t͡ʃandala',  't͡ʃandera', 'kandɛla',   'kandöla',   'kandela',   'mɔkul',     'mɔkolo',     'kandɛla',    'kandela',    'kandea',     'kandela',    'kandea',     'kandea',     'kandela',    'kandela',    'kandela',    'kandea',     'kandea',     'kandela',    'kandela',    'kandɛla',     'kandea',     'kandɛa',            'kandea',    'kandela',    'kandea',    'kandela',    'kandea',          'kandeƚa',       'kandea',    'kandea'],
				['t͡ʃaveil',   't͡ʃaji',    't͡ʃavɛl',   't͡ʃavel',   't͡ʃavel',   't͡ʃavel',   'kavel',      'kavel',      'kavɛl',      'kavɛl',      'kavel',      'kavel',      'kaveo',      'kavejo',     'kavɛl',      'kavejo',     'kavejo',     'kavejo',     'kavel',      'kavejo',     'kavejo',      'kavel',      'kavejo',            'kaveo',     'kaveo',      'kaveo',     'kavejo',     'kaveju',          'kavejo',        'kavejo',    'kaveo'],
				['t͡ʃapel',    't͡ʃapɛl',   't͡ʃapel',   't͡ʃapel',   't͡ʃapɛl',   't͡ʃapɛl',   'kapɛ',       'kapɛl',      'kapɛl',      'kapɛl',      'kapɛl',      'kapɛl',      'kapɛo',      'kapɛlo',     'kapɛl',      'kapɛlo',     'kapɛo',      'kapɛl',      'kapɛl',      'kapɛlo',     'kapɛlo',      'kapɛl',      'kapɛo',             'kapɛo',     'kapɛ',       'kapɛl',     'kapɛl',      'kapɛo',           'kapɛƚo',        'kapɛo',     'kapɛo'],
				['t͡ʃoura',    't͡ʃɔura',   't͡ʃaura',   't͡ʃaura',   't͡ʃaura',   't͡ʃaura',   'kavra',      'kaura',      'kaura',      'kavera',     'kaura',      'kavra',      'kavra',      'kavra',      'kavra',      'kavra',      'kavara',     'kavra',      'kaura',      'kavra',      'kavra',       'kavara',     'kavara',            'kavara',    'kavara',     'kavara',    'kavara',     'kavara',          'kavara',        'kavara',    'kavara'],
				['t͡ʃarbon',   'karbon',    't͡ʃarbon',  't͡ʃarbon',  't͡ʃarbon',  't͡ʃarbon',  'karbon',     'karbon',     'garbon',     'karbon',     'karbon',     'karbon',     'karbon',     'karbon',     'karbou',     'karbon',     'karbon',     'karbon',     'karbon',     'karbon',     'karbon',      'karbon',     'karbon',            'karbone',   'karbon',     'karbon',    'karbon',     'karbon',          'karbon',        'karbon',    'karbon'],
				['t͡ʃɛrn',     'karne',     'karni',     't͡ʃarne',   't͡ʃarne',   'karne',     'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',      'karne',       'karne',      'karne',             'karne',     'karne',      'karne',     'karne',      'karne',           'karne',         'karne',     'karne'],
				['t͡ʃɛr',      'karo',      'karu',      'karo',      'karo',      't͡ʃaru',    'karo',       'kar',        'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',        'karo',       'karo',              'karo',      'karo',       'karo',      'karo',       'karu',            'karo',          'karu',      'karo'],
				['t͡ʃar',      't͡ʃar',     't͡ʃar',     't͡ʃɛr',     't͡ʃar',     't͡ʃar',     'karo',       'kar',        'kar',        'kar',        'kar',        'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'karo',       'kar',        'karo',       'karo',        'karo',       'karo',              'karo',      'karo',       'karo',      'karo',       'karu',            'karo',          'karu',      'karo'],
				['morona',     't͡ʃadena',  't͡ʃadena',  't͡ʃadöna',  't͡ʃadena',  't͡ʃaðena',  'kadena',     'kaðena',     'kaðena',     'kadena',     'kadena',     'kadena',     'kaena',      'kadena',     'kadena',     'kadena',     'kaena',      'kaɛna',      'kaðena',     'kaena',      'kaena',       'kadena',     'kaena',             'kaena',     'kadena',     'kadena',    'kadena',     'kadena',          'kaena',         'kaena',     'kaena'],
				['t͡ʃaval',    'kàal',      't͡ʃaval',   't͡ʃaval',   't͡ʃaval',   't͡ʃaval',   'kaval',      'kaval',      'kaval',      'kaval',      'kaval',      'kaval',      'kavaƚo',     'kavalo',     'kaval',      'kavalo',     'kavaƚo',     'kaval',      'kaval',      'kavalo',     'kavalo',      'kaval',      'kavaƚo',            'kavaƚo',    'kaval',      'kaval',     'kaval',      'kavaƚo',          'kavaƚo',        'kavaƚo',    'kavaƚo'],
				['t͡ʃender',   'zendre',    'θender',    'θönder',    'θendre',    'θendre',    'senar',      'θender',     'θendro',     'sendre',     'θendro',     'sɛnere',     'sɛnere',     'senare',     'sendre',     'senare',     'senare',     'sendre',     'θendre',     'senare',     'senare',      'senere',     'senare',            'senere',    'sendre',     'senere',    'senda',      'senare',          'senare',        'senare',    'senere'],
				['t͡ʃant',     'zento',     'θentu',     'θentu',     'θento',     'θentu',     'sento',      'θento',      'θento',      'sento',      'θento',      'sento',      'sento',      'sento',      'sɛnto',      'sento',      'sento',      'sento',      'θento',      'sento',      'sento',       'sento',      'sento',             'sento',     'sɛnto',      'sento',     'θento',      'θento',           'θento',         'θento',     'sento'],

				['t͡ʃara',     'zera',      'θɛra',      'θöra',      'θera',      'θera',      't͡ʃera',     'θera',       'θera',       'sera',       'θera',       't͡ʃera',     'sera',       'sera',       't͡ʃera',     't͡ʃɛra',     't͡ʃɛra',     'sera',       'θera',       't͡ʃɛra',     't͡ʃɛra',      'sera',       'sɛra',              'sera',      'sera',       't͡ʃera',    't͡ʃera',     'sera',            'sera',          't͡ʃera',    'sera'],
				['t͡ʃarkle',   't͡ʃert͡ʃo', 'θert͡ʃu',   'θert͡ʃo',   'θert͡ʃo',   'θert͡ʃu',   'serkolo',    'θerkol',     'θert͡ʃo',    'serkol',     'θert͡ʃo',    'sert͡ʃo',    'sert͡ʃo',    'sert͡ʃo',    'serkol',     'sert͡ʃo',    't͡ʃert͡ʃo',  'sɛrt͡ʃo',    'θert͡ʃo',    'sɛrt͡ʃo',    'sɛrt͡ʃo',     'sert͡ʃol',   'sɛrt͡ʃo',           'sert͡ʃo',   'serkolo',    'sɛrt͡ʃo',   't͡ʃert͡ʃo',  'sert͡ʃu',         'sert͡ʃo',       'sert͡ʃo',   'sert͡ʃo'],
				['no',         'no',        'un',        'n',         'no',        'no',        'nɔ',         'nɔ',         'nɔ',         'no',         'nɔ',         'nɔ',         'nɔ',         'no',         'no',         'nɔ',         'no',         'no',         'nɔ',         'no',         'nɔ',          'no',         'nu',                'no',        'no',         'no',        'no',         'nɔ',              'no',            'nɔ',        'no'],
				['savɔve',     'sae',       'savau',     'savau',     'savɛo',     'savɛo',     'savevo',     'savɛi',      'savea',      'save',       'savɛe',      'savee',      'savevo',     'savɛo',      'savevo',     'saevo',      'saeo',       'saɛvo',      'save',       'savevo',     'savevo',      'savɛe',      'savevo',            'savevo',    'saea',       'saveo',     'savea',      'savɛvo',          'savea',         'saveo',     'savea'],
				['ke',         'ke',        'k',         'k',         'ke',        'ke',        'kɛ',         'ke',         'ke',         'ke',         'ke',         'ke',         'kɛ',         'ke',         'ke',         'kɛ',         'k',          'ke',         'ke',         'k',          'ke',          'ga',         'ke',                'ke',        'ke',         'ke',        'kɛ',         'kɛ',              'k',             'gɛ',        'ke'],
				['mɔrt',       'mɔrto',     'mɔrto',     'mɔrto',     'mɔrto',     'mɔrtu',     'mɔrto',      'mɔrt',       'mɔrth',      'mɔrt',       'mɔrt',       'mɔrt',       'mɔrto',      'mɔrto',      'mɔrto',      'mɔrto',      'mɔrt',       'mɔrto',      'mɔrt',       'mɔrto',      'mɔrto',       'mɔrt',       'mɔrto',             'mɔrto',     'mɔrto',      'mɔrto',     'mɔrto',      'mɔrto',           'mɔrto',         'mɔrto',     'mɔrto'],
				['kle',        't͡ʃae',     't͡ʃai',     't͡ʃai',     't͡ʃave',    't͡ʃave',    't͡ʃave',     't͡ʃaf',      't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',     't͡ʃave',      't͡ʃave',     't͡ʃave',            't͡ʃave',    't͡ʃave',     't͡ʃave',    't͡ʃave',     't͡ʃave',          't͡ʃave',        't͡ʃave',    't͡ʃave'],
				['t͡ʃel',      't͡ʃjel',    'θjel',      'θjel',      'θjelo',     'θjel',      't͡ʃel',      'θiɛl',       't͡ʃelo',     't͡ʃelo',     'θjɛl',       't͡ʃɛl',      'sjɛo',       't͡ʃelo',     't͡ʃɛl',      't͡ʃɛlo',     't͡ʃɛo',      't͡ʃɛl',      't͡ʃelo',     'sjelo',      't͡ʃɛlo',      't͡ʃɛl',      't͡ʃɛo',             't͡ʃelo',    't͡ʃel',      't͡ʃɛl',     't͡ʃel',      'siɛlo',           'sjeƚo',         't͡ʃɛo',     'sjel'],
				['t͡ʃarjexja', 't͡ʃarjexa', 'θarjexa',   'θareda',    'θarjexa',   'θarjexa',   'sirexa',     'θarjɛxa',    'θarexa',     'sarexa',     'θarexa',     'sarɛxa',     'sarjexa',    'sarexa',     'sirexa',     'sarɛxa',     'sarɛxa',     'sjarɛxa',    'θarjexa',    'sjarɛxa',    'sarexa',      'sarɛxa',     'sarɛxa',            'sarjɛxa',   'sirexa',     'sarɛxa',    'sirexa',     'sarɛxa',          'sarɛxa',        'sarɛxa',    'sarɛxa'],
				['t͡ʃinkanta', 'zinkwanta', 'θinkwanta', 'θinkwanta', 'θinkwanta', 'θinkwanta', 'sinkwanta',  'θinkwanta',  'θinkwanta',  'sinkwanta',  'θinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'sinkwanta',  'θinkwanta',  'sinkwanta',  'sinkwanta',   'sinkwanta',  'sinkwanta',         'sinkwanta', 'sinkwanta',  'sinkwanta', 'sinkwanta',  'sinkwanta',       'sinkwanta',     'sinkwanta', 'sinkwanta'],
				['t͡ʃink',     'zinke',     'θinki',     'θinke',     'θinke',     'θinke',     'sinkwe',     'θink',       'θinkwe',     'sinkwe',     'θinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'θinkwe',     'sinkwe',     'sinkwe',      'sinkwe',     'sinkwe',            'sinkwe',    'sinkwe',     'sinkwe',    'sinkwe',     'sinkwe',          'sinkwe',        'sinkwe',    'sinkwe'],
				['t͡ʃeola',    'zeola',     'θeula',     'θödla',     'θɛula',     'θeola',     'seola',      'θeola',      'θeola',      'segola',     'θeola',      'segoƚa',     'segoƚa',     'sɛula',      'seola',      'seola',      'seoja',      'sagoja',     'θeola',      'seola',      'seola',       'seoƚa',      'seoƚa',             'seoƚa',     'seola',      'segoƚa',    'seola',      'segwe',           'seoƚa',         'segwea',    'segoƚa'],
				['kurtel',     'kortɛl',    'gurtel',    'kortel',    'kortɛl',    'gortɛl',    'kortɛl',     'kortɛl',     'kortɛl',     'kortɛl',     'kortɛl',     'kortɛl',     'kortɛo',     'kortɛlo',    'kortɛl',     'kortɛlo',    'kortɛo',     'kortɛl',     'kortɛl',     'kortɛlo',    'kortɛlo',     'kortɛl',     'kortɛo',            'kortɛo',    'kortɛl',     'kortɛl',    'kortɛl',     'kortɛo',          'kortɛo',        'kortɛo',    'kortɛl'],
				['ʃkomint͡ʃe', 'ʃkomenza',  'skumanθa',  'skumiθje',  'skominθja', 'skomenθa',  'skominsjar', 'skomiθja',   'ʃkomiθjar',  'skominsjar', 'skominθjar', 'kominsjar',  'skominsjar', 'kumisjare',  'ʃkomisjar',  'ʃkumisjare', 'skumisjare', 'skuminsjar', 'ʃkumiθjar',  'skomisjare', 'skominsjare', 'skuminsjar', 'komisjare',         'kuminʃjar', 'skomisjar',  'komisjar',  'skomiʃjar',  'kuminsjar',       'skumiʃjar',     'komiʃjare', 'skominsjar'],
				['kontent',    'parswaso',  'kuntentu',  'kontento',  'kontɛnto',  'kuntɛnto',  'kontɛnto',   'kontent',    'kontent',    'kontɛnt',    'kontɛnt',    'kontento',   'kontento',   'kontento',   'kontɛnto',   'kontɛnto',   'kontento',   'kontento',   'kontent',    'kontɛnto',   'kontɛnto',    'kontɛnto',   'kontento',          'kontento',  'kontɛnto',   'kontɛnto',  'kontento',   'kontɛnto',        'kontɛnto',      'kontɛnto',  'kontento'],
				['kujɛrkle',   'kwɛrt͡ʃo',  'kwɛrt͡ʃu',  'kwɛrt͡ʃo',  'kwɛrt͡ʃo',  'kwɛrt͡ʃu',  'koɛrt͡ʃolu', 'kwɛrkol',    'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kovɛrt͡ʃo',  'kovɛrt͡ʃo',  'kwɛrt͡ʃo',   'kwɛrt͡ʃol',  'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kwɛrt͡ʃo',   'kovɛrt͡ʃo',  'kwɛrt͡ʃo',    'kwɛrt͡ʃo',   'kovɛrt͡ʃo',         'kovɛrt͡ʃo', 'kwɛrt͡ʃolo', 'kovɛrt͡ʃo', 'kwɛrt͡ʃolo', 'kwɛrt͡ʃu',        'kwɛrt͡ʃo',      'kwɛrt͡ʃo',  'kwɛrt͡ʃo'],
				['kɔrn',       'kɔrno',     'kɔrnu',     'kɔrno',     'kɔrno',     'kɔrno',     'kɔrno',      'kɔrn',       'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrno',      'kɔrn',       'kɔrno',      'kɔrno',       'kɔrno',      'kɔrno',             'kɔrno',     'kɔrno',      'kɔrno',     'kɔrno',      'kɔrnu',           'kɔrno',         'kɔrno',     'kɔrno'],
				['vat͡ʃa',     'armenta',   'vat͡ʃa',    'vat͡ʃa',    'vat͡ʃa',    'vat͡ʃa',    'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',       'vaka',        'vaka',       'vaka',              'vaka',      'vaka',       'vaka',      'vaka',       'vaka',            'vaka',          'vaka',      'vaka'],
				['doi',        'doi',       'ðɔi',       'dɔi',       'doi',       'ðoi',       'du',         'dɔi',        'doi',        'do',         'doi',        'du',         'dɔ',         'du',         'du',         'du',         'dɔ',         'dɔ',         'ðɔ',         'du',         'du',          'dɔ',         'do',                'do',        'du',         'du',        'du',         'du',              'du',            'du',        'do'],
				['kwosa',      'kɔʃa',      'kwisa',     'köisa',     'gangul',    'galɔn',     'galɔn',      'galɔn',      'galɔn',      'kulata',     'kɔsa',       'kwart',      'kosata',     'galɔn',      'galɔn',      'galɔn',      'kɔsja',      'kujata',     'slaka',      'galon',      'galon',       'kuƚata',     'kuƚata',            'kuƚata',    'galon',      'kɔsja',     'kosjata',    'kɔsja',           'ganba',         'kɔsja',     'kuƚata'],
				['kot',        'koto',      'kwetu',     'kötu',      'kwɔto',     'kwɔto',     'kɔto',       'kɔt',        'kɔt',        'kɔt',        'kɔt',        'kɔt',        'kɔto',       'kɔto',       'kɔt',        'kɔto',       'kɔto',       'kuxina',     'kɔt',        'kɔto',       'kɔto',        'kɔt',        'kɔto',              'kɔto',      'kɔto',       'kuxina',    'kɔto',       'kɔto',            'kɔto',          'kɔto',      'kɔto'],
				['krouʃ',      'kroʃ',      'kroxi',     'kros',      'kros',      'kros',      'krɔxe',      'kros',       'kroxe',      'kroxe',      'kros',       'kroxe',      'kroxe',      'kroxe',      'kros',       'krot͡ʃe',    'kroxe',      'kroxe',      'kros',       'kroxe',      'kroxe',       'kroxe',      'kroxe',             'kroxe',     'krot͡ʃe',    'kroxe',     'krot͡ʃe',    'kroxe',           'kroxe',         'kroxe',     'kroxe'],
				['kuna',       'kuna',      'kune',      'kuna',      'kuna',      'kuna',      'kuna',       'kuna',       'kuna',       'kuna',       'kuna',       'kuna',       'kuƚa',       'kuna',       'kuna',       'kuna',       'kua',        'kuna',       'kuna',       'kuna',       'kuna',        'kuna',       'kuna',              'kuna',      'kuna',       'kuna',      'kuna',       'kuna',            'kuna',          'kuna',      'kuna'],
				['kwɔxe',      'koe',       'kui',       'köi',       'kuxina',    'kwɔxe',     'koxar',      'koxe',       'kuxinar',    'kuxinar',    'kuxinar',    'kuxinar',    'kuxinar',    'kuxinare',   'koxer',      'kuxinare',   'kuxinare',   'kuxinar',    'kuxinar',    'kuxinare',   'kuxinare',    'kuxinar',    'kuxinare',          'kuxinar',   'koxere',     'kuxinar',   'koxar',      'kuxinar',         'kuxinare',      'kuxinare',  'kuxinar'],
				['kwor',       'kwɔre',     'kweri',     'köre',      'kwor',      'kwɔr',      'kɔr',        'kɔr',        'kɔr',        'kɔr',        'kɔr',        'kwɔr',       'kwɔr',       'kɔre',       'kɔr',        'kɔre',       'kɔre',       'kɔr',        'kor',        'kɔre',       'kɔre',        'kor',        'kore',              'kwɔr',      'kor',        'kwɔr',      'kɔr',        'kɔr',             'kwɔre',         'kwɔre',     'kɔr'],
				['me',         'mɛ',        'me',        'mɛ',        'mɛ',        'me',        'me',         'me',         'me',         'me',         'me',         'me',         'mɛ',         'me',         'mɛ',         'mɛ',         'mɛ',         'me',         'me',         'me',         'me',          'me',         'me',                'me',        'mɛ',         'me',        'me',         'mɛ',              'me',            'mɛ',        'me'],
				['fɛʃ',        'fɛʃ',       'fa',        'fa',        'fɛi',       'fax',       'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',          'fa',         'fa',                'fa',        'fa',         'fa',        'fa',         'fa',              'fa',            'fa',        'fa'],
				['mɛl',        'mal',       'mal',       'mal',       'mal',       'mal',       'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'mal',        'ma',         'mal',        'mal',        'male',       'mal',         'mal',        'ma',                'mal',       'mal',        'mal',       'mal',        'ma',              'mae',           'mae',       'mal'],
				['dent',       'dɛnte',     'dentu',     'dento',     'ðɛnte',     'dɛnti',     'dɛnte',      'dent',       'dent',       'dɛnt',       'dent',       'dente',      'dente',      'dente',      'dent',       'dɛnte',      'dente',      'dente',      'dent',       'dɛnte',      'dɛnte',       'dent',       'dɛnte',             'dente',     'dɛnte',      'dente',     'dente',      'dɛnte',           'dɛnte',         'dɛnte',     'dente'],
				['al',         'ɔm',        'ɔn',        'ɔn',        'ɔn',        'ɔn',        'ɔmu',        'ɔm',         'ɔn',         'ɔn',         'ɔn',         'ɔn',         'ɔmo',        'ɔmo',        'ɔm',         'ɔmo',        'ɔmo',        'ɔmo',        'ɔm',         'ɔmo',        'ɔmo',         'ɔn',         'ɔmo',               'ɔmo',       'ɔmo',        'ɔmo',       'ɔmo',        'ɔmo',             'ɔmo',           'ɔmo',       'ɔmo'],
				['trantadoi',  'trɛntadoi', 'trɛntaðoi', 'trentadɔi', 'trentadoi', 'trɛntaðɔi', 'trentadu',   'trentadɔi',  'trentaðoi',  'trentadɔ',   'trentaðoi',  'trentado',   'trentado',   'trentadu',   'trentadu',   'trentadu',   'trentadɔ',   'trentado',   'trentaðɔ',   'trentadu',   'trentadu',    'trentadɔ',   'trentadɔ',          'trentado',  'trentadu',   'trentadɔ',  'trentadu',   'trentadu',        'trentado',      'trentaðɔ',  'trentado'],
				['dents',      'dɛntes',    'ðenti',     'dente',     'dɛnte',     'ðenti',     'dɛnti',      'dɛnti',      'ðenth',      'dɛnt',       'dent',       'denti',      'denti',      'denti',      'denti',      'dɛnti',      'denti',      'denti',      'ðent',       'dɛnti',      'denti',       'dent',       'dɛnti',             'denti',     'dɛnti',      'denti',     'denti',      'dɛnti',           'dɛnti',         'dɛnti',     'denti'],
				['darta',      'dreta',     'destre',    'destra',    'dɛstra',    'ðreta',     'drita',      'dɛstra',     'dɛstra',     'dɛstra',     'dreta',      'dɛstra',     'dɛstra',     'destra',     'drita',      'dɛstra',     'dɛstra',     'dɛstra',     'dɛstra',     'dɛstra',     'dɛstra',      'dɛstra',     'dɛstra',            'dɛstra',    'dɛstra',     'dɛstra',    'drita',      'drita',           'dɛstra',        'dɛstra',    'drita'],
				['ades',       'adɛs',      'aðes',      'ades',      'aðɛs',      'ades',      'adeso',      'aðɛs',       'aðɛs',       'adɛs',       'aðɛs',       'adɛs',       'dɛso',       'adeso',      'adɛs',       'dɛso',       'adɛso',      'dɛso',       'aðɛs',       'dɛso',       'dɛso',        'adɛs',       'dɛso',              'adɛs',      'adɛso',      'adɛso',     'adɛso',      'adɛso',           'dɛso',          'adɛso',     'dɛso'],
				['t',          't',         't',         'in',        'te',        't',         'tɛ',         't',          'te',         'tu',         'te',         'tɛ',         'ti',         'tɛ',         'tɛ',         'tɛ',         'tɛ',         'te',         'tu',         'te',         'tɛ',          'te',         'te',                'te',        'tɛ',         'te',        'te',         'te',              'tɛ',            'te',        'te'],
				['mus',        'as',        'ax',        'ax',        'vas',       'ax',        'gɛ',         'a',          'a',          'a',          'a',          'dɛve',       'ga',         'ge',         'ge',         'ga',         'gɛ',         'ge',         'a',          'gɛ',         'gɛ',          'devi',       'gɛ',                'ga',        'gɛ',         'ga',        'gɛ',         'gɛ',              'gɛ',            'gɛ',        'ga'],
				['zi',         'zi',        'ði',        'di',        'ði',        'di',        'andar',      'andar',      'andar',      'andar',      'andar',      'andar',      'andar',      'anare',      'nar',        'nare',       'anare',      'andar',      'andar',      'nare',       'nar',         'ndar',       'andare',            'andar',     'nar',        'andar',     'andar',      'andar',           'nare',          'andar',     'ndar'],
				['dezenber',   'dezɛnbre',  'deθenbar',  'diθenbre',  'deθenbre',  'deθenbre',  'dit͡ʃɛnbre', 'dit͡ʃɛnbre', 'dit͡ʃenbre', 'dit͡ʃɛnbre', 'deθɛnbre',   'dit͡ʃenbre', 'dit͡ʃɛnbre', 'disenbre',   'dit͡ʃenbre', 'dit͡ʃɛnbre', 'disenbre',   'disenbre',   'dit͡ʃɛnbre', 'disɛnbre',   'disɛnbre',    'dit͡ʃɛnbre', 'disɛnbre',          'disenbre',  'dit͡ʃɛnbre', 'disenbre',  'dit͡ʃenbre', 'desɛnbre',        'desɛnbre',      'disɛnbre',  'desenbre'],
				['dexdɔt',     'dixdɔto',   'dixdɔtu',   'dixdɔto',   'dixdɔto',   'dixdɔto',   'dixdɔto',    'dixdɔt',     'dit͡ʃɔto',   'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',    'dixdɔto',     'dixdɔto',    'dixdɔto',           'dixdɔto',   'dixdɔto',    'dixdɔto',   'dixdɔto',    'dixdɔto',         'dixdɔto',       'dixdɔto',   'dixdɔto'],
				['dieʃ',       'djeʃ',      'djɛs',      'djös',      'djexe',     'djexe',     'djexe',      'djɛs',       'djɛxe',      'djexe',      'djɛxe',      'djɛxe',      'djexe',      'djexe',      'djexe',      'djɛxe',      'djɛxe',      'djexe',      'djɛxe',      'djexe',      'djɛxe',       'djɛxe',      'djɛxe',             'djɛxe',     'djexe',      'djɛxe',     'djexe',      'djɛxe',           'djɛxe',         'djɛxe',     'djɛxe'],
				['di',         'di',        'di',        'di',        'di',        'ði',        'dir',        'di',         'dir',        'dir',        'dir',        'dir',        'dir',        'dire',       'di',         'dire',       'dire',       'dir',        'dir',        'dire',       'dire',        'dir',        'dire',              'dir',       'dir',        'dir',       'dir',        'dir',             'dire',          'dire',      'dir'],
				['mi',         'jo',        'jɔ',        'jö',        'jo',        'jɔ',        'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',         'mi',          'mi',         'mi',                'mi',        'mi',         'mi',        'mi',         'mi',              'mi',            'mi',        'mi'],
				['al',         'el',        'li',        'li',        'lui',       'al',        'el',         'ɛl',         'l',          'l',          'l',          'ɛl',         'ɛl',         'el',         'ɛl',         'l',          'eo',         'lu',         'l',          'el',         'el',          'lu',         'lu',                'lu',        'l',          'lu',        'el',         'el',              'el',            'lu',        'el'],
				['dige',       'digo',      'digi',      'digo',      'ðigo',      'ðio',       'digo',       'dige',       'dige',       'dixe',       'dige',       'dixe',       'digo',       'digo',       'digo',       'digo',       'digo',       'dixo',       'dige',       'digo',       'digo',        'dixe',       'digo',              'digo',      'digo',       'digo',      'digo',       'digo',            'digu',          'digo',      'digo'],
				['diʃ',        'diʃ',       'dis',       'dis',       'dis',       'dis',       'dixe',       'dis',        'dis',        'dixe',       'dis',        'dixe',       'dixe',       'dixe',       'dis',        'dixe',       'dixe',       'dixe',       'dis',        'dixe',       'dixe',        'dixe',       'dixe',              'dixe',      'dixe',       'dixe',      'dixe',       'dixe',            'dixe',          'dixe',      'dixe'],
				['dit',        'dito',      'ðitu',      'dito',      'dito',      'ðito',      'dito',       'dit',        'dith',       'dita',       'dita',       'dit',        'dito',       'dito',       'dit',        'dito',       'ito',        'dito',       'ðit',        'dito',       'dito',        'dita',       'dito',              'dito',      'dito',       'dito',      'dito',       'dito',            'dito',          'dito',      'dito'],
				['ledɛl',      'deda',      'ðedal',     'dedal',     'dedal',     'deðal',     'djal',       'dedal',      'diðjal',     'didjal',     'deðjal',     'didjal',     'dixjal',     'deale',      'djal',       'deale',      'dixjae',     'deal',       'diðjal',     'deale',      'deale',       'didjal',     'ditae',             'dixjae',    'djal',       'didjal',    'deal',       'deal',            'dixjae',        'dixjae',    'didjal'],
				['deit',       'djedo',     'dɛiðu',     'döido',     'deðo',      'diðo',      'deo',        'det',        'deth',       'det',        'det',        'deo',        'deo',        'deo',        'djɛl',       'deo',        'deo',        'dɛo',        'det',        'deo',        'deo',         'deo',        'dɛo',               'deo',       'djɛl',       'deo',       'deo',        'dɛo',             'deo',           'deo',       'deo'],
				['deit͡ʃ',     'djede',     'ðɛidi',     'döide',     'deðe',      'djeðe',     'dei',        'det',        'ðeth',       'det',        'dɛt',        'dɛi',        'dei',        'dei',        'dijɛi',      'dei',        'de',         'dei',        'ðɛt',        'dei',        'dei',         'dei',        'dɛi',               'dɛe',       'djɛi',       'dei',       'dei',        'dɛi',             'dei',           'dii',       'dei'],
				['t͡ʃink',     'zinke',     'θink',      'θink',      'θinke',     'θinke',     'sinkwe',     'θink',       'θinkwe',     'sinkwe',     'θinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'sinkwe',     'zinkwe',     'θinkwe',     'sinkwe',     'sinkwe',      'singwe',     'sinkwe',            'sinkwe',    'sinkwe',     'sinkwe',    'sinkwe',     'sinkwe',          'sinkwe',        'sinkwe',    'sinkwe'],
				['dodeʃ',      'dɔdeʃ',     'dɔðes',     'dodes',     'dodexe',    'dɔðexe',    'dɔdexe',     'dɔdes',      'dɔðexe',     'dɔdexe',     'dɔdexe',     'dɔdexe',     'dɔdexe',     'dɔdexe',     'dodexe',     'dɔdexe',     'dodexe',     'dodaxe',     'dɔðexe',     'dodexe',     'dodexe',      'dɔdexe',     'dodexe',            'dodexe',    'dodexe',     'dɔdexe',    'dodexe',     'dodexe',          'dodaxe',        'dɔdexe',    'dodexe'],
				['dout͡ʃ',     'dɔlze',     'dɔlθi',     'dolθe',     'dolθe',     'ðɔlθ',      'dɔlse',      'dɔθ',        'dɔlθ',       'dɔls',       'dɔlθ',       'dɔls',       'dɔlse',      'dolse',      'dolz',       'dɔlse',      'dolse',      'dolze',      'dɔlθ',       'dolse',      'dolse',       'dɔls',       'dolse',             'dolse',     'dolso',      'dolse',     'dolse',      'dɔse',            'dɔlse',         'dɔlse',     'dolse'],
				['doman',      'doman',     'duman',     'doman',     'doman',     'doman',     'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔman',      'dɔma',       'dɔman',      'doman',      'dɔman',      'dɔman',      'dɔman',      'doman',       'dɔman',      'dɔman',             'doman',     'doman',      'doman',     'doman',      'dɔman',           'diman',         'dɔman',     'diman'],
				['domanja',    'domeɲa',    'dumɛnja',   'dmöɲa',     'domeɲa',    'ðomeɲa',    'domɛnika',   'domɛnega',   'ðomenega',   'domenega',   'domenega',   'domenega',   'domenega',   'domenega',   'domenika',   'domenega',   'domenega',   'domenega',   'domenega',   'domenega',   'domenega',    'domɛnega',   'domenega',          'domenega',  'duminika',   'domenega',  'duminika',   'domɛnega',        'domɛnega',      'domɛnega',  'domenega'],
				['doi',        'doi',       'dɔi',       'dɔi',       'doi',       'doi',       'du',         'dɔi',        'doi',        'dɔ',         'dɔi',        'dɔ',         'dɔ',         'du',         'du',         'dɔ',         'dɔ',         'du',         'dɔ',         'dɔ',         'du',          'dɔ',         'dɔ',                'do',        'du',         'dɔ',        'du',         'do',              'do',            'dɔ',        'do'],
				['ɔi',         'ɔme',       'ɔmi',       'ɔmin',      'ɔmins',     'ɔme',       'ɔmini',      'ɔmin',       'ɔmi',        'ɔmini',      'ɔn',         'ɔmini',      'ɔmeni',      'ɔmeni',      'ɔmini',      'ɔmini',      'ɔmini',      'ɔmini',      'ɔmi',        'ɔmeni',      'ɔmini',       'ɔmeni',      'ɔmini',             'ɔmeni',     'omeni',      'ɔmeni',     'ɔmini',      'ɔmani',           'ɔmani',         'ɔmeni',     'ɔmi'],
				['fɔmena',     'femena',    'fɛmena',    'fömna',     'femena',    'femena',    'femena',     'fɛmena',     'femena',     'femena',     'femena',     'femena',     'femena',     'femena',     'femena',     'femena',     'fɛmena',     'femena',     'femena',     'femena',     'femena',      'fɛmena',     'fɛmena',            'femena',    'femena',     'femena',    'femena',     'fɛmena',          'femena',        'femena',    'femena'],
				['fɔmene',     'femenes',   'fɛmeni',    'fömne',     'femene',    'femene',    'femene',     'fɛmene',     'femene',     'femene',     'femene',     'femene',     'femene',     'femene',     'femene',     'femene',     'fɛmene',     'femene',     'femene',     'femene',     'femene',      'femene',     'fɛmene',            'femene',    'femene',     'fɛmene',    'femene',     'fɛmene',          'femene',        'femene',    'femene'],
				['dur',        'duro',      'duru',      'duro',      'ðuro',      'ðuru',      'duro',       'dur',        'dur',        'dur',        'dur',        'duro',       'duro',       'duro',       'dur',        'duro',       'duro',       'duro',       'dur',        'duro',       'duro',        'duro',       'duro',              'duro',      'duro',       'duro',      'duro',       'duro',            'duro',          'duru',      'duro'],
				['strak',      'ʃtrako',    'straku',    'strako',    'strako',    'strako',    'strako',     'strak',      'strakh',     'strak',      'strak',      'strak',      'strako',     'jako',       'strak',      'jako',       'stufo',      'stanko',     'strakh',     'strako',     'jako',        'stuf',       'stufo',             'stufo',     'strako',     'stufo',     'strako',     'strako',          'strako',        'strako',    'strako'],
				['iʃte',       'iʃtade',    'istjaði',   'istede',    'istjade',   'istaðe',    'ista',       'ista',       'ista',       'ista',       'ista',       'ista',       'ista',       'esta',       'ista',       'ista',       'ista',       'ista',       'ista',       'ista',       'ista',        'ista',       'ista',              'ista',      'ista',       'ista',      'ista',       'ista',            'ista',          'ista',      'ista'],
				['fɛver',      'fɔuro',     'fauru',     'fauro',     'fauro',     'fauro',     'fabro',      'faure',      'fabro',      'favero',     'faore',      'fabro',      'fabro',      'majaro',     'ferar',      'feraro',     'favaro',     'favro',      'fauro',      'favro',      'favaro',      'favaro',     'favero',            'favero',    'ferar',      'favero',    'feraro',     'favero',          'favaro',        'favaro',    'favaro'],
				['faut͡ʃ',     'fɔut͡ʃe',   'fauθi',     'fauθe',     'fauθe',     'fauθ',      'fɛro',       'fauθ',       'falθ',       'faldin',     'falθ',       'sexue',      'falt͡ʃe',    'sexolɔto',   'fɛr',        'falt͡ʃeto',  'falsa',      'false',      'falθ',       'false',      'falsa',       'faldin',     'falsa',             'falsin',    'fɛro',       'falsin',    'falt͡ʃeto',  'segeto',          'mesora',        'fɛro',      'falsin'],
				['sjɛrf',      'adɔra',     'sɛrvi',     'sɛrve',     'sɛrve',     'sɛrve',     'okɔr',       'dɔra',       'ðɔpera',     'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',      'dɔpera',     'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',      'sɛrve',       'sɛrve',      'sɛrve',             'sɛrve',     'dɔpera',     'sɛrve',     'dɔpera',     'sɛrve',           'sɛrve',         'sɛrve',     'dɔpera'],
				['sije',       'taja',      'taje',      'taje',      'sea',       'sea',       'tajar',      'sjɛga',      'tajar',      'tajar',      'tajar',      'taja',       'tad͡ʒare',   'tajare',     'tajar',      'tajar',      'taja',       'taja',       'tajar',      'falsar',     'tajare',      'tajar',      'tajar',             'tajar',     'tajar',      'tajar',     'tajar',      'tajare',          'tajar',         'tajare',    'tajar'],
				['fam',        'fame',      'fami',      'fame',      'fame',      'fame',      'fame',       'fam',        'fan',        'fan',        'fan',        'fame',       'fame',       'fame',       'fam',        'fame',       'fame',       'fame',       'fam',        'fame',       'fame',        'fame',       'fame',              'fame',      'fame',       'fame',      'fame',       'fame',            'fame',          'fame',      'fame'],
				['ɛ',          'ei',        'ai',        'ei',        'ɛi',        'ɛi',        'gɔ',         'ai',         'ɔ',          'ɔ',          'ɔ',          'ɔ',          'gɔ',         'gɔ',         'gɔ',         'gɔ',         'gɔ',         'gɔ',         'ɔ',          'gɔ',         'gɔ',          'ɔ',          'gɔ',                'gɔ',        'gɔ',         'gɔ',        'gɔ',         'gɔ',              'gɔ',            'gɔ',        'gɔ'],
				['fɛ',         'fei',       'fɛi',       'foi',       'fɛi',       'fɛi',       'far',        'fa',         'far',        'far',        'far',        'far',        'far',        'fare',       'far',        'fare',       'fare',       'far',        'far',        'fare',       'fare',        'far',        'fare',              'far',       'far',        'far',       'far',        'far',             'fare',          'fare',      'far'],
				['fɛze',       'fɛzo',      'faθi',      'faθo',      'fɛzo',      'faθo',      'fɔ',         'faθe',       'fae',        'fae',        'fae',        'fae',        'faso',       'faso',       'faso',       'faso',       'faso',       'faso',       'fae',        'faso',       'faso',        'fae',        'faso',              'faso',      'fao',        'fae',       'fao',        'fao',             'faso',          'faso',      'faso'],
				['fɛs',        'fɛʃ',       'fa',        'fa',        'fɛs',       'fas',       'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',         'fa',          'fa',         'fa',                'fa',        'fa',         'fa',        'fa',         'fa',              'fa',            'fa',        'fa'],
				['fat',        'fato',      'fatu',      'fato',      'fato',      'fato',      'fato',       'fat',        'fat',        'fat',        'fat',        'fat',        'fato',       'fato',       'fat',        'fato',       'fato',       'fato',       'fat',        'fato',       'fato',        'fat',        'fato',              'fato',      'fato',       'fato',      'fato',       'fato',            'fato',          'fato',      'fato'],
				['faure',      'febraro',   'febraru',   'foröi',     'febraru',   'febraro',   'febrar',     'febrajo',    'febrajo',    'febrajo',    'fevrɛr',     'febrajo',    'febrajo',    'febraro',    'fevrar',     'febraro',    'febraro',    'fevraro',    'febrajo',    'febraro',    'febraro',     'febraro',    'febraro',           'febraro',   'febrar',     'febraro',   'febrar',     'febraru',         'fevraro',       'febraro',   'febraro'],
				['fjɛrn',      'fɛr',       'fɛru',      'fɛro',      'fɛr',       'fɛr',       'fɛro',       'fɛr',        'fɛr',        'fɛr',        'fɛr',        'fɛro',       'fɛro',       'fɛro',       'fɛr',        'fɛro',       'fɛro',       'fɛr',        'fɛr',        'fɛro',       'fɛro',        'fɛro',       'fɛro',              'fɛro',      'fɛro',       'fɛro',      'fɛro',       'fɛru',            'fɛro',          'fɛro',      'fɛro'],
				['deʃtude',    'ʃtudar',    'destuxe',   'estude',    'despea',    'ðestuda',   'xmorsar',    'destuxa',    'stuxar',     'stuxar',     'stuxar',     'stuar',      'stuar',      'xmorsar',    'xmorsar',    'xmorsare',   'xmorsare',   'xmorsar',    'stuxar',     'smorsare',   'xmorsare',    'stuxar',     'stuar',             'stuar',     'xmorsar',    'stua',      'xmorzar',    'dexmorsar',       'xmorsare',      'stuar',     'stuar'],
				['fen',        'fen',       'fjen',      'föɲ',       'fjɛn',      'fen',       'fjɛn',       'fɛn',        'fjɛn',       'fjɛn',       'fen',        'fjɛn',       'fjen',       'fen',        'fe',         'fen',        'fen',        'fen',        'fɛn',        'fjɛn',       'fen',         'fen',        'fɛn',               'fen',       'fɛn',        'fen',       'fjen',       'fen',             'fen',           'fen',       'fen'],
				['fjol',       'fjol',      'fi',        'fi',        'fjol',      'fjɔl',      'fjɔl',       'fjɔl',       'fjɔl',       'fjɔl',       'fjɔl',       'fjɔl',       'fio',        'fjɔlo',      'fjɔl',       'fjɔlo',      'fjɔjo',      'fjɔl',       'fjɔl',       'fjɔjo',      'fjɔlo',       'fjɔl',       'fjɔƚo',             'fjɔl',      'fjɔl',       'fjɔl',      'fjɔl',       'fjɔjo',           'fjɔƚo',         'fjɔjo',     'fjɔl'],
				['fil',        'firo',      'filu',      'filo',      'filo',      'filo',      'fil',        'fil',        'fil',        'fil',        'fil',        'fil',        'fiƚo',       'filo',       'fil',        'filo',       'fiƚo',       'fil',        'fil',        'filo',       'filo',        'fil',        'fiƚo',              'fiƚo',      'fil',        'fiƚo',      'filo',       'fiƚu',            'filu',          'fijo',      'fil'],
				['t͡ʃɔf',      'fjɔr',      'fjɔr',      'fjɔr',      'fjor',      'fjɔr',      'fjɔr',       'fjɔr',       'fjɔr',       'fjɔr',       'fjɔr',       'fjɔr',       'fjɔr',       'fjɔre',      'fjɔr',       'fjɔre',      'fjore',      'fjɔr',       'fjɔr',       'fjɔre',      'fjɔre',       'fjɔr',       'fjɔre',             'fjɔr',      'fjɔr',       'fjɔr',      'fjɔr',       'fjor',            'fjore',         'fjɔre',     'fjor'],
				['foja',       'foja',      'fɔja',      'fɔja',      'fɔja',      'fwoja',     'foja',       'foja',       'foja',       'foja',       'foja',       'fɔja',       'fɔd͡ʒa',     'fɔja',       'foja',       'fɔja',       'fɔja',       'foja',       'foja',       'fɔja',       'fɔja',        'fɔja',       'fɔja',              'fɔja',      'foja',       'fɔja',      'foja',       'fɔja',            'fɔja',          'fɔja',      'fɔja'],
				['foje',       'fojes',     'fɔi',       'fɔi',       'fɔe',       'fwoje',     'foje',       'foje',       'foje',       'foje',       'foje',       'fɔje',       'fɔd͡ʒe',     'fɔje',       'foje',       'fɔje',       'fɔje',       'foje',       'foje',       'fɔje',       'fɔje',        'fɔje',       'fɔje',              'fɔje',      'foe',        'fɔje',      'foje',       'fɔje',            'fɔje',          'fɔje',      'fɔje'],
				['pjɛrt',      'pɛrde',     'pɛrd',      'pɛrd',      'pɛrde',     'pɛrde',     'mɔla',       'pɛrθ',       'pɛrðe',      'pɛrθ',       'perθ',       'pɛrd',       'pɛrde',      'pɛrde',      'pɛrde',      'pɛrde',      'pɛrd',       'pɛrde',      'pɛrθ',       'pɛrde',      'pɛrde',       'pɛrde',      'pɛrde',             'pɛrde',     'pɛrde',      'pɛrde',     'pɛrde',      'pɛrde',           'pɛrde',         'pɛrde',     'pɛrde'],
				['fradel',     'fardɛl',    'fra',       'fra',       'fraðɛl',    'farðɛl',    'fradɛl',     'fraðɛl',     'fraðɛl',     'fradɛl',     'farðɛl',     'fradɛl',     'fradɛƚo',    'fradelo',    'fradɛl',     'fradelo',    'fradɛƚo',    'fradɛl',     'fraðɛl',     'fradɛjo',    'fradɛlo',     'fraðɛl',     'fradɛƚo',           'fradɛƚo',   'fradɛl',     'fradɛl',    'fradɛl',     'fraðɛƚo',         'fradɛƚo',       'fraðɛƚo',   'fradɛl'],
				['fret',       'fjedo',     'frɛiðu',    'fröido',    'freðo',     'fjeðo',     'fredo',      'frɛt',       'fret',       'frɛt',       'frɛt',       'fredo',      'fredo',      'fredo',      'frɛ',        'fredo',      'fredo',      'fredo',      'fret',       'frɛdo',      'fredo',       'frɛðo',      'fredo',             'fredo',     'fredo',      'fredo',     'fredo',      'frɛðo',           'freðo',         'freðo',     'fredo'],
				['fum',        'fun',       'fumu',      'fumo',      'fumo',      'fun',       'fumo',       'fum',        'fun',        'fun',        'fun',        'fumo',       'fumo',       'fumo',       'fum',        'fumo',       'fumo',       'fumo',       'fum',        'fumo',       'fumo',        'fun',        'fumo',              'fumo',      'fumo',       'fumo',      'fumo',       'fumo',            'fumo',          'fumo',      'fumo'],
				['fonk',       'fonza',     'fɔngu',     'fongo',     'fɔngo',     'fongol',    'fɔngo',      'fɔnk',       'fongo',      'fɔnk',       'fonk',       'fungo',      'fungo',      'fungo',      'fɔng',       'fungo',      'bujo',       'fongo',      'fɔnk',       'fungo',      'fungo',       'fongo',      'fongo',             'fongo',     'fongo',      'fungo',     'fɔngo',      'fungo',           'fungo',         'fungo',     'fongo'],
				['fuɔk',       'fɔ',        'fwɛgu',     'fögo',      'fwɔgo',     'fwo',       'fogo',       'fɔk',        'fogo',       'fogo',       'fok',        'fɔgo',       'fogo',       'fogo',       'fɔgo',       'fɔgo',       'fɔgo',       'fogo',       'fogo',       'fɔgo',       'fɔgo',        'fɔgo',       'fɔgo',              'fɔgo',      'fɔgo',       'fɔgo',      'fogo',       'fɔgo',            'fɔgo',          'fɔgo',      'fɔgo'],
				['gal',        'xal',       'gɛl',       'd͡ʒel',     'd͡ʒal',     'gal',       'gal',        'gal',        'gal',        'gal',        'gal',        'gal',        'gaƚo',       'galo',       'gal',        'galo',       'gaƚo',       'gal',        'gal',        'galo',       'galo',        'gal',        'gaƚo',              'gaƚo',      'gal',        'gal',       'galo',       'gaƚo',            'gaƚo',          'gaƚo',      'gal'],
				['pita',       'pita',      'pite',      'pita',      'pita',      'pita',      'galina',     'pita',       'pita',       'pita',       'pita',       'gaina',      'gaina',      'galina',     'galina',     'galina',     'gaina',      'gaina',      'pita',       'galina',     'galina',      'gaina',      'gaina',             'gaina',     'galina',     'gaina',     'galina',     'gaina',           'galina',        'gaina',     'pita'],
				['d͡ʒama',     'xanba',     'd͡ʒanbɲ',   'd͡ʒanba',   'd͡ʒanba',   'ganba',     'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',      'ganba',       'ganba',      'ganba',             'ganba',     'ganba',      'ganba',     'ganba',      'ganba',           'ganba',         'ganba',     'ganba'],
				['rota',       'rota',      'rota',      'rota',      'rota',      'rota',      'rɔta',       'rota',       'rota',       'rota',       'rota',       'rota',       'rota',       'rota',       'rota',       'rɔta',       'rɔta',       'rota',       'rota',       'rota',       'rɔta',        'rota',       'rɔta',              'rota',      'rota',       'rota',      'rota',       'rota',            'rota',          'rota',      'rota'],
				['d͡ʒat',      'xato',      'd͡ʒetu',    'd͡ʒet',     'gato',      'gat',       'gato',       'gat',        'gat',        'gat',        'gat',        'gat',        'gato',       'gato',       'gat',        'gato',       'gato',       'gato',       'gat',        'gato',       'gato',        'gat',        'gato',              'gato',      'gato',       'gato',      'gato',       'gato',            'gato',          'gato',      'gato'],
				['xenɛ',       'xenaro',    'd͡ʒenaju',  'd͡ʒenaro',  'd͡ʒenaro',  'jenaro',    'xenar',      'd͡ʒenajo',   'd͡ʒenajo',   'd͡ʒenajo',   'ðenɛr',      'd͡ʒenaro',   'd͡ʒenajo',   'd͡ʒenaro',   'd͡ʒenar',    'd͡ʒenaro',   'xenajo',     'jenaro',     'd͡ʒenaro',   'xenaro',     'd͡ʒenaro',    'zenaro',     'xenaro',            'xenaro',    'xenar',      'xenaro',    'd͡ʒenar',    'xenaro',          'xenaro',        'jenaro',    'xenaro'],
				['xenogle',    'xenɔjo',    'dunɔjo',    'donojo',    'denojo',    'ðenojo',    'xenɔt͡ʃo',   'danɔt͡ʃo',   'denɔt͡ʃo',   'xenɔt͡ʃo',   'denɔt͡ʃo',   'xenɔt͡ʃo',   'xenɔt͡ʃo',   'xenɔt͡ʃo',   'xenɔt͡ʃo',   'genɔt͡ʃ',    'xanɔt͡ʃo',   'xenɔt͡ʃo',   'denɔt͡ʃo',   'denɔt͡ʃo',   'xanɔt͡ʃo',    'xenɔt͡ʃo',   'xenɔt͡ʃo',          'xenɔt͡ʃo',  'xenɔt͡ʃo',   'xenɔt͡ʃo',  'xenɔt͡ʃo',   'xenɔt͡ʃo',        'denɔt͡ʃo',      'xenɔt͡ʃo',  'xenɔt͡ʃo'],
				['xwɔk',       'xɔgo',      'dwegu',     'dögo',      'dwogo',     'ðwogo',     'xugo',       'dugo',       'dogo',       'dɔgo',       'dugo',       'xɔgo',       'xɔgo',       'xugo',       'xugo',       'xugo',       'xugo',       'xugo',       'dugo',       'dugo',       'xugo',        'xɔgo',       'd͡ʒogo',            'djɔgo',     'xugo',       'xjɔgo',     'xugo',       'xɔgu',            'dwɔgo',         'xɔgu',      'xɔgo'],
//				['',     '',       '',      '',        '',       '',       '',      '',          '',     '',     '',       '',         '',      '',          '',        '',         '',    '',     '',     '',      '',      '',        '',                '',      '',      '',    '',     '',              '',            '',       ''],
//				['',     '',       '',      '',        '',       '',       '',      '',          '',     '',     '',       '',         '',      '',          '',        '',         '',    '',     '',     '',      '',      '',        '',                '',      '',      '',    '',     '',              '',            '',       ''],
//				['',     '',       '',      '',        '',       '',       '',      '',          '',     '',     '',       '',         '',      '',          '',        '',         '',    '',     '',     '',      '',      '',        '',                '',      '',      '',    '',     '',              '',            '',       ''],
//				['',     '',       '',      '',        '',       '',       '',      '',          '',     '',     '',       '',         '',      '',          '',        '',         '',    '',     '',     '',      '',      '',        '',                '',      '',      '',    '',     '',              '',            '',       ''],
//				'Rèba',        'Cortina',   'Padola',    'Costalta',  'Auronzo',   'Pozzale',   'Verona',     'Cencenighe', 'Casan',      'Tarzo',      'Belluno',    'San Stino',  'Venezia',    'Crespadoro', 'Albisano',   'Montebello', 'Teolo',      'Romano',     'Vas',        'Tonezza',    'Vicenza',     'Lovadina',   'Campo San Martino', 'Istrana',   'Raldon',     'Meolo',     'Cerea',      'Fratta Polesine', 'Villa Estense', 'Cavarzare', 'Treviso'],
			],
			size = variants.length,
			matrix = [],
			costs = {
				insertion: 1,
				deletion: 1,
				modification: 0.5,
				matchingFn: function(from, to, costs){
					//return (from == to? 0: costs.modification);
					if(from == to)
						return 0;
					var fromFeatures = Phone.convertStringIntoFeatures(from),
						toFeatures = Phone.convertStringIntoFeatures(to),
						differences = Phone.compareFeatures(fromFeatures[0], toFeatures[0], true).diff;
					return costs.modification + differences.length / Phone.numberOfSegments();/**/
				}
			},
			//costs = {insertion: 1, deletion: 1, modification: 0.5},
			i, j;
		for(i = 0; i < size; i ++){
			matrix[i] = [];
			matrix[i][i] = 0;
		}

		words = words.map(function(word){
			return word.map(function(w){
				return w.match(Phone.REGEX_UNICODE_SPLITTER);
			});
		});

		//calculate average of distances
		words.forEach(function(word){
			for(i = 0; i < size; i ++)
				for(j = i + 1; j < size; j ++)
					matrix[i][j] = (matrix[i][j] || 0) + StringDistance.getStructuralDistance(word[i], word[j], costs);
		});
		for(i = 0; i < size; i ++)
			for(j = i + 1; j < size; j ++)
				matrix[i][j] /= words.length;

		//cluster variants
		var clusteredVariants = Clusterer.cluster(matrix, variants);

		equal(clusteredVariants, '((((((((((Campo San Martino|Romano)|Meolo)|Venezia)|Istrana)|((Montebello|Vicenza)|(Tonezza|Villa Estense)))|Teolo)|Cavarzare)|Fratta Polesine)|(((((Cerea|Verona)|Crespadoro)|Raldon)|((San Stino|Tarzo)|Lovadina))|(((Belluno|Casan)|Cencenighe)|(Albisano|Vas))))|(((((Auronzo|Costalta)|Padola)|Rɛba)|Pozzale)|Cortina))');
	});
});
